// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Core(	// @[src/main/core/Core.scala:23:7]
  input         clock,	// @[src/main/core/Core.scala:23:7]
                reset,	// @[src/main/core/Core.scala:23:7]
  output [31:0] io_imem_araddr,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_arvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_imem_arready,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_imem_arid,	// @[src/main/core/Core.scala:24:16]
  output [7:0]  io_imem_arlen,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_imem_arsize,	// @[src/main/core/Core.scala:24:16]
  output [1:0]  io_imem_arburst,	// @[src/main/core/Core.scala:24:16]
  input  [31:0] io_imem_rdata,	// @[src/main/core/Core.scala:24:16]
  input         io_imem_rvalid,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_rready,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_imem_awaddr,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_awvalid,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_imem_awid,	// @[src/main/core/Core.scala:24:16]
  output [7:0]  io_imem_awlen,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_imem_awsize,	// @[src/main/core/Core.scala:24:16]
  output [1:0]  io_imem_awburst,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_imem_wdata,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_imem_wstrb,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_wvalid,	// @[src/main/core/Core.scala:24:16]
                io_imem_wlast,	// @[src/main/core/Core.scala:24:16]
                io_imem_bready,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_dmem_araddr,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_arvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_arready,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_dmem_arsize,	// @[src/main/core/Core.scala:24:16]
  input  [31:0] io_dmem_rdata,	// @[src/main/core/Core.scala:24:16]
  input  [1:0]  io_dmem_rresp,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_rvalid,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_rready,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_dmem_awaddr,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_awvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_awready,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_dmem_awsize,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_dmem_wdata,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_dmem_wstrb,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_wvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_wready,	// @[src/main/core/Core.scala:24:16]
  input  [1:0]  io_dmem_bresp,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_bvalid,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_bready	// @[src/main/core/Core.scala:24:16]
);

  wire        _GEN;	// @[src/main/core/Core.scala:280:{34,56}, :326:22]
  wire        _GEN_0;	// @[src/main/core/Core.scala:279:{34,56}, :326:22]
  wire        _GEN_1;	// @[src/main/core/Core.scala:278:{34,56}, :326:22]
  wire        _icache_io_in_arready;	// @[src/main/core/Core.scala:59:24]
  wire [31:0] _icache_io_in_rdata;	// @[src/main/core/Core.scala:59:24]
  wire        _icache_io_in_rvalid;	// @[src/main/core/Core.scala:59:24]
  wire        _icache_fencei_io_vr_is_fencei_io_ready;	// @[src/main/core/Core.scala:59:24]
  wire [1:0]  _wbu_io_gpr_wen;	// @[src/main/core/Core.scala:33:21]
  wire [4:0]  _wbu_io_gpr_addr;	// @[src/main/core/Core.scala:33:21]
  wire [31:0] _wbu_io_gpr_wdata;	// @[src/main/core/Core.scala:33:21]
  wire [11:0] _wbu_io_csr_addr;	// @[src/main/core/Core.scala:33:21]
  wire [2:0]  _wbu_io_csr_cmd;	// @[src/main/core/Core.scala:33:21]
  wire [31:0] _wbu_io_csr_wdata;	// @[src/main/core/Core.scala:33:21]
  wire        _wbu_io_is_irq;	// @[src/main/core/Core.scala:33:21]
  wire [3:0]  _wbu_io_irq_num;	// @[src/main/core/Core.scala:33:21]
  wire        _wbu_io_irq_valid;	// @[src/main/core/Core.scala:33:21]
  wire        _wbu_io_pipe_in_ready;	// @[src/main/core/Core.scala:33:21]
  wire        _lsu_io_pipe_in_ready;	// @[src/main/core/Core.scala:32:21]
  wire        _lsu_io_pipe_out_valid;	// @[src/main/core/Core.scala:32:21]
  wire [31:0] _lsu_io_pipe_out_bits_ls2wb_reg_pc;	// @[src/main/core/Core.scala:32:21]
  wire [4:0]  _lsu_io_pipe_out_bits_ls2wb_wb_addr;	// @[src/main/core/Core.scala:32:21]
  wire [1:0]  _lsu_io_pipe_out_bits_ls2wb_rf_wen;	// @[src/main/core/Core.scala:32:21]
  wire [31:0] _lsu_io_pipe_out_bits_ls2wb_wb_data;	// @[src/main/core/Core.scala:32:21]
  wire [31:0] _lsu_io_pipe_out_bits_ls2wb_csr_wdata;	// @[src/main/core/Core.scala:32:21]
  wire [11:0] _lsu_io_pipe_out_bits_ls2wb_csr_addr;	// @[src/main/core/Core.scala:32:21]
  wire [2:0]  _lsu_io_pipe_out_bits_ls2wb_csr_cmd;	// @[src/main/core/Core.scala:32:21]
  wire        _lsu_io_pipe_out_bits_ls2wb_is_irq;	// @[src/main/core/Core.scala:32:21]
  wire [3:0]  _lsu_io_pipe_out_bits_ls2wb_irq_num;	// @[src/main/core/Core.scala:32:21]
  wire        _exu_io_br_flg;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_jmp_flg;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_br_target;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_alu_out;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_pipe_in_ready;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_pipe_out_valid;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_reg_pc;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_op1_data;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_rs2_data;	// @[src/main/core/Core.scala:31:21]
  wire [4:0]  _exu_io_pipe_out_bits_exe2ls_wb_addr;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_alu_out;	// @[src/main/core/Core.scala:31:21]
  wire [1:0]  _exu_io_pipe_out_bits_exe2ls_rf_wen;	// @[src/main/core/Core.scala:31:21]
  wire [2:0]  _exu_io_pipe_out_bits_exe2ls_wb_sel;	// @[src/main/core/Core.scala:31:21]
  wire [11:0] _exu_io_pipe_out_bits_exe2ls_csr_addr;	// @[src/main/core/Core.scala:31:21]
  wire [2:0]  _exu_io_pipe_out_bits_exe2ls_csr_cmd;	// @[src/main/core/Core.scala:31:21]
  wire [1:0]  _exu_io_pipe_out_bits_exe2ls_mem_wen;	// @[src/main/core/Core.scala:31:21]
  wire [2:0]  _exu_io_pipe_out_bits_exe2ls_mem_op;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_pipe_out_bits_exe2ls_is_irq;	// @[src/main/core/Core.scala:31:21]
  wire [3:0]  _exu_io_pipe_out_bits_exe2ls_irq_num;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_csr_rdata;	// @[src/main/core/Core.scala:31:21]
  wire [4:0]  _idu_io_gpr_rs1_addr;	// @[src/main/core/Core.scala:30:21]
  wire [4:0]  _idu_io_gpr_rs2_addr;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_gpr_rs1_is_read;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_gpr_rs2_is_read;	// @[src/main/core/Core.scala:30:21]
  wire [11:0] _idu_io_csr_raddr;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_is_mret;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_pipe_in_ready;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_pipe_out_valid;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_reg_pc;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_op1_data;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_op2_data;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_rs2_data;	// @[src/main/core/Core.scala:30:21]
  wire [4:0]  _idu_io_pipe_out_bits_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21]
  wire [1:0]  _idu_io_pipe_out_bits_id2exe_rf_wen;	// @[src/main/core/Core.scala:30:21]
  wire [4:0]  _idu_io_pipe_out_bits_id2exe_exe_fun;	// @[src/main/core/Core.scala:30:21]
  wire [2:0]  _idu_io_pipe_out_bits_id2exe_wb_sel;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_imm_b_sext;	// @[src/main/core/Core.scala:30:21]
  wire [11:0] _idu_io_pipe_out_bits_id2exe_csr_addr;	// @[src/main/core/Core.scala:30:21]
  wire [2:0]  _idu_io_pipe_out_bits_id2exe_csr_cmd;	// @[src/main/core/Core.scala:30:21]
  wire [1:0]  _idu_io_pipe_out_bits_id2exe_mem_wen;	// @[src/main/core/Core.scala:30:21]
  wire [2:0]  _idu_io_pipe_out_bits_id2exe_mem_op;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_pipe_out_bits_id2exe_is_irq;	// @[src/main/core/Core.scala:30:21]
  wire [3:0]  _idu_io_pipe_out_bits_id2exe_irq_num;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_csr_rdata;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_fencei_io_vr_is_fencei_io_valid;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_fencei_io_vr_is_fencei_io_bits_is_fencei;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _ifu_io_imem_araddr;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_imem_arvalid;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_imem_rready;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_pipe_in_ready;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_pipe_out_valid;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _ifu_io_pipe_out_bits_if2id_reg_pc;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _ifu_io_pipe_out_bits_if2id_inst;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _csr_io_csr_mtvec;	// @[src/main/core/Core.scala:27:21]
  wire [31:0] _csr_io_csr_mepc;	// @[src/main/core/Core.scala:27:21]
  wire [31:0] _csr_io_csr_rdata;	// @[src/main/core/Core.scala:27:21]
  wire [31:0] _gpr_io_gpr_rs1_data;	// @[src/main/core/Core.scala:26:21]
  wire [31:0] _gpr_io_gpr_rs2_data;	// @[src/main/core/Core.scala:26:21]
  reg         ready_r;	// @[src/main/core/Core.scala:41:26]
  reg         ifu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:42:38]
  reg  [31:0] idu_io_pipe_in_bits_r_if2id_reg_pc;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] idu_io_pipe_in_bits_r_if2id_inst;	// @[src/main/core/Core.scala:325:33]
  reg         idu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:326:34]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_reg_pc;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_op1_data;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_op2_data;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_rs2_data;	// @[src/main/core/Core.scala:325:33]
  reg  [4:0]  exu_io_pipe_in_bits_r_id2exe_wb_addr;	// @[src/main/core/Core.scala:325:33]
  reg  [1:0]  exu_io_pipe_in_bits_r_id2exe_rf_wen;	// @[src/main/core/Core.scala:325:33]
  reg  [4:0]  exu_io_pipe_in_bits_r_id2exe_exe_fun;	// @[src/main/core/Core.scala:325:33]
  reg  [2:0]  exu_io_pipe_in_bits_r_id2exe_wb_sel;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_imm_b_sext;	// @[src/main/core/Core.scala:325:33]
  reg  [11:0] exu_io_pipe_in_bits_r_id2exe_csr_addr;	// @[src/main/core/Core.scala:325:33]
  reg  [2:0]  exu_io_pipe_in_bits_r_id2exe_csr_cmd;	// @[src/main/core/Core.scala:325:33]
  reg  [1:0]  exu_io_pipe_in_bits_r_id2exe_mem_wen;	// @[src/main/core/Core.scala:325:33]
  reg  [2:0]  exu_io_pipe_in_bits_r_id2exe_mem_op;	// @[src/main/core/Core.scala:325:33]
  reg         exu_io_pipe_in_bits_r_id2exe_is_irq;	// @[src/main/core/Core.scala:325:33]
  reg  [3:0]  exu_io_pipe_in_bits_r_id2exe_irq_num;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_csr_rdata;	// @[src/main/core/Core.scala:325:33]
  reg         exu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:326:34]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_reg_pc;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_op1_data;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_rs2_data;	// @[src/main/core/Core.scala:325:33]
  reg  [4:0]  lsu_io_pipe_in_bits_r_exe2ls_wb_addr;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_alu_out;	// @[src/main/core/Core.scala:325:33]
  reg  [1:0]  lsu_io_pipe_in_bits_r_exe2ls_rf_wen;	// @[src/main/core/Core.scala:325:33]
  reg  [2:0]  lsu_io_pipe_in_bits_r_exe2ls_wb_sel;	// @[src/main/core/Core.scala:325:33]
  reg  [11:0] lsu_io_pipe_in_bits_r_exe2ls_csr_addr;	// @[src/main/core/Core.scala:325:33]
  reg  [2:0]  lsu_io_pipe_in_bits_r_exe2ls_csr_cmd;	// @[src/main/core/Core.scala:325:33]
  reg  [1:0]  lsu_io_pipe_in_bits_r_exe2ls_mem_wen;	// @[src/main/core/Core.scala:325:33]
  reg  [2:0]  lsu_io_pipe_in_bits_r_exe2ls_mem_op;	// @[src/main/core/Core.scala:325:33]
  reg         lsu_io_pipe_in_bits_r_exe2ls_is_irq;	// @[src/main/core/Core.scala:325:33]
  reg  [3:0]  lsu_io_pipe_in_bits_r_exe2ls_irq_num;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_csr_rdata;	// @[src/main/core/Core.scala:325:33]
  reg         lsu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:326:34]
  reg  [31:0] wbu_io_pipe_in_bits_r_ls2wb_reg_pc;	// @[src/main/core/Core.scala:325:33]
  reg  [4:0]  wbu_io_pipe_in_bits_r_ls2wb_wb_addr;	// @[src/main/core/Core.scala:325:33]
  reg  [1:0]  wbu_io_pipe_in_bits_r_ls2wb_rf_wen;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] wbu_io_pipe_in_bits_r_ls2wb_wb_data;	// @[src/main/core/Core.scala:325:33]
  reg  [31:0] wbu_io_pipe_in_bits_r_ls2wb_csr_wdata;	// @[src/main/core/Core.scala:325:33]
  reg  [11:0] wbu_io_pipe_in_bits_r_ls2wb_csr_addr;	// @[src/main/core/Core.scala:325:33]
  reg  [2:0]  wbu_io_pipe_in_bits_r_ls2wb_csr_cmd;	// @[src/main/core/Core.scala:325:33]
  reg         wbu_io_pipe_in_bits_r_ls2wb_is_irq;	// @[src/main/core/Core.scala:325:33]
  reg  [3:0]  wbu_io_pipe_in_bits_r_ls2wb_irq_num;	// @[src/main/core/Core.scala:325:33]
  reg         wbu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:326:34]
  wire        exu_is_working = ~_exu_io_pipe_in_ready | _GEN_1;	// @[src/main/core/Core.scala:31:21, :127:{26,48}, :278:{34,56}, :326:22]
  wire        lsu_is_working = ~_lsu_io_pipe_in_ready | _GEN_0;	// @[src/main/core/Core.scala:32:21, :128:{26,48}, :279:{34,56}, :326:22]
  wire        wbu_is_working = ~_wbu_io_pipe_in_ready | _GEN;	// @[src/main/core/Core.scala:33:21, :129:{26,48}, :280:{34,56}, :326:22]
  reg         wbu_is_working_r;	// @[src/main/core/Core.scala:130:35]
  wire        wbu_end_flg = wbu_is_working_r & ~wbu_is_working;	// @[src/main/core/Core.scala:129:48, :130:35, :131:{40,42}]
  reg         wbu_end_flg_r;	// @[src/main/core/Core.scala:132:32]
  reg         exu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:339:41]
  wire        _exu_raw_rs1_T =
    _idu_io_gpr_rs1_addr == exu_io_pipe_in_bits_r_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21, :325:33, :329:48]
  wire        _exu_raw_rs2_T =
    _idu_io_gpr_rs2_addr == exu_io_pipe_in_bits_r_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21, :325:33, :329:48]
  wire        exu_raw =
    (_idu_io_gpr_rs1_is_read & (|_idu_io_gpr_rs1_addr) & _exu_raw_rs1_T
     | _idu_io_gpr_rs2_is_read & (|_idu_io_gpr_rs2_addr) & _exu_raw_rs2_T)
    & exu_is_working & exu_io_pipe_in_bits_r_id2exe_rf_wen == 2'h1
    & exu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:30:21, :127:48, :139:132, :325:33, :329:48, :334:31, :335:31, :339:41, :340:{39,65,97,146}]
  reg         lsu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:339:41]
  wire        _lsu_raw_rs1_T =
    _idu_io_gpr_rs1_addr == lsu_io_pipe_in_bits_r_exe2ls_wb_addr;	// @[src/main/core/Core.scala:30:21, :325:33, :329:48]
  wire        _lsu_raw_rs2_T =
    _idu_io_gpr_rs2_addr == lsu_io_pipe_in_bits_r_exe2ls_wb_addr;	// @[src/main/core/Core.scala:30:21, :325:33, :329:48]
  wire        lsu_raw =
    (_idu_io_gpr_rs1_is_read & (|_idu_io_gpr_rs1_addr) & _lsu_raw_rs1_T
     | _idu_io_gpr_rs2_is_read & (|_idu_io_gpr_rs2_addr) & _lsu_raw_rs2_T)
    & lsu_is_working & lsu_io_pipe_in_bits_r_exe2ls_rf_wen == 2'h1
    & lsu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:30:21, :128:48, :139:132, :140:132, :325:33, :329:48, :334:31, :335:31, :339:41, :340:{39,65,97,146}]
  reg         wbu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:339:41]
  wire        _wbu_raw_rs1_T =
    _idu_io_gpr_rs1_addr == wbu_io_pipe_in_bits_r_ls2wb_wb_addr;	// @[src/main/core/Core.scala:30:21, :325:33, :329:48]
  wire        _wbu_raw_rs2_T =
    _idu_io_gpr_rs2_addr == wbu_io_pipe_in_bits_r_ls2wb_wb_addr;	// @[src/main/core/Core.scala:30:21, :325:33, :329:48]
  wire        wbu_raw =
    (_idu_io_gpr_rs1_is_read & (|_idu_io_gpr_rs1_addr) & _wbu_raw_rs1_T
     | _idu_io_gpr_rs2_is_read & (|_idu_io_gpr_rs2_addr) & _wbu_raw_rs2_T)
    & wbu_is_working & wbu_io_pipe_in_bits_r_ls2wb_rf_wen == 2'h1
    & wbu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:30:21, :129:48, :139:132, :141:130, :325:33, :329:48, :334:31, :335:31, :339:41, :340:{39,65,97,146}]
  wire        is_raw = exu_raw | lsu_raw | wbu_raw;	// @[src/main/core/Core.scala:142:37, :340:146]
  wire        exu_raw_rs1 = exu_raw & _exu_raw_rs1_T;	// @[src/main/core/Core.scala:143:31, :329:48, :340:146]
  wire        exu_raw_rs2 = exu_raw & _exu_raw_rs2_T;	// @[src/main/core/Core.scala:144:31, :329:48, :340:146]
  wire        lsu_raw_rs1 = lsu_raw & _lsu_raw_rs1_T;	// @[src/main/core/Core.scala:145:31, :329:48, :340:146]
  wire        lsu_raw_rs2 = lsu_raw & _lsu_raw_rs2_T;	// @[src/main/core/Core.scala:146:31, :329:48, :340:146]
  wire        wbu_raw_rs1 = wbu_raw & _wbu_raw_rs1_T;	// @[src/main/core/Core.scala:147:31, :329:48, :340:146]
  wire        wbu_raw_rs2 = wbu_raw & _wbu_raw_rs2_T;	// @[src/main/core/Core.scala:148:31, :329:48, :340:146]
  wire        rs1_raw = exu_raw_rs1 | lsu_raw_rs1 | wbu_raw_rs1;	// @[src/main/core/Core.scala:143:31, :145:31, :147:31, :149:46]
  wire        rs2_raw = exu_raw_rs2 | lsu_raw_rs2 | wbu_raw_rs2;	// @[src/main/core/Core.scala:144:31, :146:31, :148:31, :150:46]
  reg         rs1_raw_valid;	// @[src/main/core/Core.scala:165:32]
  reg         rs2_raw_valid;	// @[src/main/core/Core.scala:166:32]
  reg  [4:0]  rs1_raw_rd;	// @[src/main/core/Core.scala:168:25]
  reg  [4:0]  rs2_raw_rd;	// @[src/main/core/Core.scala:169:25]
  reg         rs1_resolved_r;	// @[src/main/core/Core.scala:206:33]
  reg         rs2_resolved_r;	// @[src/main/core/Core.scala:207:33]
  reg         is_irq;	// @[src/main/core/Core.scala:256:25]
  reg         exu_out_valid_rise_REG;	// @[src/main/core/Core.scala:264:62]
  wire        is_ctrl_hazard =
    (_exu_io_br_flg & _exu_io_br_target != _ifu_io_pipe_out_bits_if2id_reg_pc
     | _exu_io_jmp_flg & _exu_io_alu_out != _ifu_io_pipe_out_bits_if2id_reg_pc)
    & _exu_io_pipe_out_valid & ~exu_out_valid_rise_REG;	// @[src/main/core/Core.scala:29:21, :31:21, :264:{54,62}, :265:{42,62,101,120,138,178}]
  wire        _exu_io_hazard_flush_flg_T = is_ctrl_hazard | is_irq;	// @[src/main/core/Core.scala:256:25, :265:178, :269:47]
  wire        _GEN_2 = ~_exu_io_hazard_flush_flg_T & ifu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:42:{26,38}, :269:47, :276:{34,56}]
  wire        _GEN_3 = ~_exu_io_hazard_flush_flg_T & idu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:42:26, :269:47, :276:{34,56}, :277:{34,56}, :326:{22,34}]
  assign _GEN_1 = ~_exu_io_hazard_flush_flg_T & exu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:42:26, :269:47, :276:{34,56}, :278:{34,56}, :326:{22,34}]
  assign _GEN_0 = ~is_irq & lsu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:256:25, :279:{34,56}, :326:{22,34}]
  assign _GEN = ~is_irq & wbu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:256:25, :279:{34,56}, :280:{34,56}, :326:{22,34}]
  always @(posedge clock) begin	// @[src/main/core/Core.scala:23:7]
    ready_r <= _ifu_io_pipe_in_ready;	// @[src/main/core/Core.scala:29:21, :41:26]
    if (_ifu_io_pipe_out_valid & _idu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:29:21, :30:21, :325:62]
      idu_io_pipe_in_bits_r_if2id_reg_pc <= _ifu_io_pipe_out_bits_if2id_reg_pc;	// @[src/main/core/Core.scala:29:21, :325:33]
      idu_io_pipe_in_bits_r_if2id_inst <= _ifu_io_pipe_out_bits_if2id_inst;	// @[src/main/core/Core.scala:29:21, :325:33]
    end
    if (_idu_io_pipe_in_ready)	// @[src/main/core/Core.scala:30:21]
      idu_io_pipe_in_valid_r <= _ifu_io_pipe_out_valid;	// @[src/main/core/Core.scala:29:21, :326:34]
    if (_idu_io_pipe_out_valid & _exu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:30:21, :31:21, :325:62]
      exu_io_pipe_in_bits_r_id2exe_reg_pc <= _idu_io_pipe_out_bits_id2exe_reg_pc;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_op1_data <= _idu_io_pipe_out_bits_id2exe_op1_data;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_op2_data <= _idu_io_pipe_out_bits_id2exe_op2_data;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_rs2_data <= _idu_io_pipe_out_bits_id2exe_rs2_data;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_wb_addr <= _idu_io_pipe_out_bits_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_rf_wen <= _idu_io_pipe_out_bits_id2exe_rf_wen;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_exe_fun <= _idu_io_pipe_out_bits_id2exe_exe_fun;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_wb_sel <= _idu_io_pipe_out_bits_id2exe_wb_sel;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_imm_b_sext <= _idu_io_pipe_out_bits_id2exe_imm_b_sext;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_csr_addr <= _idu_io_pipe_out_bits_id2exe_csr_addr;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_csr_cmd <= _idu_io_pipe_out_bits_id2exe_csr_cmd;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_mem_wen <= _idu_io_pipe_out_bits_id2exe_mem_wen;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_mem_op <= _idu_io_pipe_out_bits_id2exe_mem_op;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_is_irq <= _idu_io_pipe_out_bits_id2exe_is_irq;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_irq_num <= _idu_io_pipe_out_bits_id2exe_irq_num;	// @[src/main/core/Core.scala:30:21, :325:33]
      exu_io_pipe_in_bits_r_id2exe_csr_rdata <= _idu_io_pipe_out_bits_id2exe_csr_rdata;	// @[src/main/core/Core.scala:30:21, :325:33]
    end
    if (_exu_io_pipe_in_ready)	// @[src/main/core/Core.scala:31:21]
      exu_io_pipe_in_valid_r <= _idu_io_pipe_out_valid;	// @[src/main/core/Core.scala:30:21, :326:34]
    if (_exu_io_pipe_out_valid & _lsu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:31:21, :32:21, :325:62]
      lsu_io_pipe_in_bits_r_exe2ls_reg_pc <= _exu_io_pipe_out_bits_exe2ls_reg_pc;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_op1_data <= _exu_io_pipe_out_bits_exe2ls_op1_data;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_rs2_data <= _exu_io_pipe_out_bits_exe2ls_rs2_data;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_wb_addr <= _exu_io_pipe_out_bits_exe2ls_wb_addr;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_alu_out <= _exu_io_pipe_out_bits_exe2ls_alu_out;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_rf_wen <= _exu_io_pipe_out_bits_exe2ls_rf_wen;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_wb_sel <= _exu_io_pipe_out_bits_exe2ls_wb_sel;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_csr_addr <= _exu_io_pipe_out_bits_exe2ls_csr_addr;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_csr_cmd <= _exu_io_pipe_out_bits_exe2ls_csr_cmd;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_mem_wen <= _exu_io_pipe_out_bits_exe2ls_mem_wen;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_mem_op <= _exu_io_pipe_out_bits_exe2ls_mem_op;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_is_irq <= _exu_io_pipe_out_bits_exe2ls_is_irq;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_irq_num <= _exu_io_pipe_out_bits_exe2ls_irq_num;	// @[src/main/core/Core.scala:31:21, :325:33]
      lsu_io_pipe_in_bits_r_exe2ls_csr_rdata <= _exu_io_pipe_out_bits_exe2ls_csr_rdata;	// @[src/main/core/Core.scala:31:21, :325:33]
    end
    if (_lsu_io_pipe_in_ready)	// @[src/main/core/Core.scala:32:21]
      lsu_io_pipe_in_valid_r <= _exu_io_pipe_out_valid;	// @[src/main/core/Core.scala:31:21, :326:34]
    if (_lsu_io_pipe_out_valid & _wbu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:32:21, :33:21, :325:62]
      wbu_io_pipe_in_bits_r_ls2wb_reg_pc <= _lsu_io_pipe_out_bits_ls2wb_reg_pc;	// @[src/main/core/Core.scala:32:21, :325:33]
      wbu_io_pipe_in_bits_r_ls2wb_wb_addr <= _lsu_io_pipe_out_bits_ls2wb_wb_addr;	// @[src/main/core/Core.scala:32:21, :325:33]
      wbu_io_pipe_in_bits_r_ls2wb_rf_wen <= _lsu_io_pipe_out_bits_ls2wb_rf_wen;	// @[src/main/core/Core.scala:32:21, :325:33]
      wbu_io_pipe_in_bits_r_ls2wb_wb_data <= _lsu_io_pipe_out_bits_ls2wb_wb_data;	// @[src/main/core/Core.scala:32:21, :325:33]
      wbu_io_pipe_in_bits_r_ls2wb_csr_wdata <= _lsu_io_pipe_out_bits_ls2wb_csr_wdata;	// @[src/main/core/Core.scala:32:21, :325:33]
      wbu_io_pipe_in_bits_r_ls2wb_csr_addr <= _lsu_io_pipe_out_bits_ls2wb_csr_addr;	// @[src/main/core/Core.scala:32:21, :325:33]
      wbu_io_pipe_in_bits_r_ls2wb_csr_cmd <= _lsu_io_pipe_out_bits_ls2wb_csr_cmd;	// @[src/main/core/Core.scala:32:21, :325:33]
      wbu_io_pipe_in_bits_r_ls2wb_is_irq <= _lsu_io_pipe_out_bits_ls2wb_is_irq;	// @[src/main/core/Core.scala:32:21, :325:33]
      wbu_io_pipe_in_bits_r_ls2wb_irq_num <= _lsu_io_pipe_out_bits_ls2wb_irq_num;	// @[src/main/core/Core.scala:32:21, :325:33]
    end
    if (_wbu_io_pipe_in_ready)	// @[src/main/core/Core.scala:33:21]
      wbu_io_pipe_in_valid_r <= _lsu_io_pipe_out_valid;	// @[src/main/core/Core.scala:32:21, :326:34]
    wbu_is_working_r <= wbu_is_working;	// @[src/main/core/Core.scala:129:48, :130:35]
    wbu_end_flg_r <= wbu_end_flg;	// @[src/main/core/Core.scala:131:40, :132:32]
    exu_raw_stage_left_valid_r <= _GEN_3;	// @[src/main/core/Core.scala:277:{34,56}, :326:22, :339:41]
    lsu_raw_stage_left_valid_r <= _GEN_3;	// @[src/main/core/Core.scala:277:{34,56}, :326:22, :339:41]
    wbu_raw_stage_left_valid_r <= _GEN_3;	// @[src/main/core/Core.scala:277:{34,56}, :326:22, :339:41]
    if (rs1_raw)	// @[src/main/core/Core.scala:149:46]
      rs1_raw_rd <=
        exu_raw_rs1
          ? exu_io_pipe_in_bits_r_id2exe_wb_addr
          : lsu_raw_rs1
              ? lsu_io_pipe_in_bits_r_exe2ls_wb_addr
              : wbu_raw_rs1 ? wbu_io_pipe_in_bits_r_ls2wb_wb_addr : 5'h0;	// @[src/main/core/Core.scala:23:7, :143:31, :145:31, :147:31, :168:25, :325:33, src/main/scala/chisel3/util/Mux.scala:126:16]
    if (rs2_raw)	// @[src/main/core/Core.scala:150:46]
      rs2_raw_rd <=
        exu_raw_rs2
          ? exu_io_pipe_in_bits_r_id2exe_wb_addr
          : lsu_raw_rs2
              ? lsu_io_pipe_in_bits_r_exe2ls_wb_addr
              : wbu_raw_rs2 ? wbu_io_pipe_in_bits_r_ls2wb_wb_addr : 5'h0;	// @[src/main/core/Core.scala:23:7, :144:31, :146:31, :148:31, :169:25, :325:33, src/main/scala/chisel3/util/Mux.scala:126:16]
    rs1_resolved_r <=
      rs1_raw_valid & wbu_end_flg & wbu_io_pipe_in_bits_r_ls2wb_wb_addr == rs1_raw_rd;	// @[src/main/core/Core.scala:131:40, :165:32, :168:25, :203:{53,90}, :206:33, :325:33]
    rs2_resolved_r <=
      rs2_raw_valid & wbu_end_flg & wbu_io_pipe_in_bits_r_ls2wb_wb_addr == rs2_raw_rd;	// @[src/main/core/Core.scala:131:40, :166:32, :169:25, :204:{53,90}, :207:33, :325:33]
    is_irq <= _wbu_io_irq_valid & _wbu_io_is_irq;	// @[src/main/core/Core.scala:33:21, :256:{25,43}]
    exu_out_valid_rise_REG <= _exu_io_pipe_out_valid;	// @[src/main/core/Core.scala:31:21, :264:62]
    if (reset) begin	// @[src/main/core/Core.scala:23:7]
      ifu_io_pipe_in_valid_r <= _GEN_2;	// @[src/main/core/Core.scala:42:{26,38}, :276:{34,56}]
      rs1_raw_valid <= 1'h0;	// @[src/main/core/Core.scala:165:32, :334:31]
      rs2_raw_valid <= 1'h0;	// @[src/main/core/Core.scala:166:32, :334:31]
    end
    else begin	// @[src/main/core/Core.scala:23:7]
      ifu_io_pipe_in_valid_r <= _ifu_io_pipe_in_ready & ready_r | ifu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:29:21, :41:26, :42:{38,90}]
      rs1_raw_valid <= ~rs1_resolved_r & (rs1_raw | rs1_raw_valid);	// @[src/main/core/Core.scala:149:46, :165:32, :180:18, :186:23, :206:33, :209:{26,41}]
      rs2_raw_valid <= ~rs2_resolved_r & (rs2_raw | rs2_raw_valid);	// @[src/main/core/Core.scala:150:46, :166:32, :191:18, :197:23, :207:33, :210:{26,41}]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/Core.scala:23:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/Core.scala:23:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/Core.scala:23:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:25];	// @[src/main/core/Core.scala:23:7]
    initial begin	// @[src/main/core/Core.scala:23:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/Core.scala:23:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/Core.scala:23:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/Core.scala:23:7]
        for (logic [4:0] i = 5'h0; i < 5'h1A; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/core/Core.scala:23:7]
        end	// @[src/main/core/Core.scala:23:7]
        ready_r = _RANDOM[5'h0][0];	// @[src/main/core/Core.scala:23:7, :41:26]
        ifu_io_pipe_in_valid_r = _RANDOM[5'h0][1];	// @[src/main/core/Core.scala:23:7, :41:26, :42:38]
        idu_io_pipe_in_bits_r_if2id_reg_pc = {_RANDOM[5'h0][31:2], _RANDOM[5'h1][1:0]};	// @[src/main/core/Core.scala:23:7, :41:26, :325:33]
        idu_io_pipe_in_bits_r_if2id_inst = {_RANDOM[5'h1][31:2], _RANDOM[5'h2][1:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        idu_io_pipe_in_valid_r = _RANDOM[5'h2][2];	// @[src/main/core/Core.scala:23:7, :325:33, :326:34]
        exu_io_pipe_in_bits_r_id2exe_reg_pc = {_RANDOM[5'h2][31:3], _RANDOM[5'h3][2:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_op1_data = {_RANDOM[5'h3][31:3], _RANDOM[5'h4][2:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_op2_data = {_RANDOM[5'h4][31:3], _RANDOM[5'h5][2:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_rs2_data = {_RANDOM[5'h5][31:3], _RANDOM[5'h6][2:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_wb_addr = _RANDOM[5'h6][7:3];	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_rf_wen = _RANDOM[5'h6][9:8];	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_exe_fun = _RANDOM[5'h6][14:10];	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_wb_sel = _RANDOM[5'h6][17:15];	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_imm_b_sext =
          {_RANDOM[5'h8][31:18], _RANDOM[5'h9][17:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_csr_addr = _RANDOM[5'hB][29:18];	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_csr_cmd = {_RANDOM[5'hB][31:30], _RANDOM[5'hC][0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_mem_wen = _RANDOM[5'hC][2:1];	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_mem_op = _RANDOM[5'hC][5:3];	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_is_irq = _RANDOM[5'hC][6];	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_irq_num = _RANDOM[5'hC][10:7];	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_bits_r_id2exe_csr_rdata =
          {_RANDOM[5'hC][31:11], _RANDOM[5'hD][10:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        exu_io_pipe_in_valid_r = _RANDOM[5'hD][11];	// @[src/main/core/Core.scala:23:7, :325:33, :326:34]
        lsu_io_pipe_in_bits_r_exe2ls_reg_pc = {_RANDOM[5'hD][31:12], _RANDOM[5'hE][11:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_op1_data =
          {_RANDOM[5'hE][31:12], _RANDOM[5'hF][11:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_rs2_data =
          {_RANDOM[5'hF][31:12], _RANDOM[5'h10][11:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_wb_addr = _RANDOM[5'h10][16:12];	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_alu_out =
          {_RANDOM[5'h10][31:17], _RANDOM[5'h11][16:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_rf_wen = _RANDOM[5'h11][18:17];	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_wb_sel = _RANDOM[5'h11][21:19];	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_csr_addr =
          {_RANDOM[5'h11][31:22], _RANDOM[5'h12][1:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_csr_cmd = _RANDOM[5'h12][4:2];	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_mem_wen = _RANDOM[5'h13][6:5];	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_mem_op = _RANDOM[5'h13][9:7];	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_is_irq = _RANDOM[5'h13][10];	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_irq_num = _RANDOM[5'h13][14:11];	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_bits_r_exe2ls_csr_rdata =
          {_RANDOM[5'h13][31:15], _RANDOM[5'h14][14:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        lsu_io_pipe_in_valid_r = _RANDOM[5'h14][15];	// @[src/main/core/Core.scala:23:7, :325:33, :326:34]
        wbu_io_pipe_in_bits_r_ls2wb_reg_pc =
          {_RANDOM[5'h14][31:16], _RANDOM[5'h15][15:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        wbu_io_pipe_in_bits_r_ls2wb_wb_addr = _RANDOM[5'h15][20:16];	// @[src/main/core/Core.scala:23:7, :325:33]
        wbu_io_pipe_in_bits_r_ls2wb_rf_wen = _RANDOM[5'h15][22:21];	// @[src/main/core/Core.scala:23:7, :325:33]
        wbu_io_pipe_in_bits_r_ls2wb_wb_data =
          {_RANDOM[5'h15][31:23], _RANDOM[5'h16][22:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        wbu_io_pipe_in_bits_r_ls2wb_csr_wdata =
          {_RANDOM[5'h16][31:23], _RANDOM[5'h17][22:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        wbu_io_pipe_in_bits_r_ls2wb_csr_addr =
          {_RANDOM[5'h17][31:23], _RANDOM[5'h18][2:0]};	// @[src/main/core/Core.scala:23:7, :325:33]
        wbu_io_pipe_in_bits_r_ls2wb_csr_cmd = _RANDOM[5'h18][5:3];	// @[src/main/core/Core.scala:23:7, :325:33]
        wbu_io_pipe_in_bits_r_ls2wb_is_irq = _RANDOM[5'h18][6];	// @[src/main/core/Core.scala:23:7, :325:33]
        wbu_io_pipe_in_bits_r_ls2wb_irq_num = _RANDOM[5'h18][10:7];	// @[src/main/core/Core.scala:23:7, :325:33]
        wbu_io_pipe_in_valid_r = _RANDOM[5'h18][11];	// @[src/main/core/Core.scala:23:7, :325:33, :326:34]
        wbu_is_working_r = _RANDOM[5'h18][12];	// @[src/main/core/Core.scala:23:7, :130:35, :325:33]
        wbu_end_flg_r = _RANDOM[5'h18][13];	// @[src/main/core/Core.scala:23:7, :132:32, :325:33]
        exu_raw_stage_left_valid_r = _RANDOM[5'h18][14];	// @[src/main/core/Core.scala:23:7, :325:33, :339:41]
        lsu_raw_stage_left_valid_r = _RANDOM[5'h18][15];	// @[src/main/core/Core.scala:23:7, :325:33, :339:41]
        wbu_raw_stage_left_valid_r = _RANDOM[5'h18][16];	// @[src/main/core/Core.scala:23:7, :325:33, :339:41]
        rs1_raw_valid = _RANDOM[5'h18][17];	// @[src/main/core/Core.scala:23:7, :165:32, :325:33]
        rs2_raw_valid = _RANDOM[5'h18][18];	// @[src/main/core/Core.scala:23:7, :166:32, :325:33]
        rs1_raw_rd = _RANDOM[5'h18][23:19];	// @[src/main/core/Core.scala:23:7, :168:25, :325:33]
        rs2_raw_rd = _RANDOM[5'h18][28:24];	// @[src/main/core/Core.scala:23:7, :169:25, :325:33]
        rs1_resolved_r = _RANDOM[5'h19][3];	// @[src/main/core/Core.scala:23:7, :206:33]
        rs2_resolved_r = _RANDOM[5'h19][4];	// @[src/main/core/Core.scala:23:7, :206:33, :207:33]
        is_irq = _RANDOM[5'h19][5];	// @[src/main/core/Core.scala:23:7, :206:33, :256:25]
        exu_out_valid_rise_REG = _RANDOM[5'h19][6];	// @[src/main/core/Core.scala:23:7, :206:33, :264:62]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/Core.scala:23:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/Core.scala:23:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  GPR gpr (	// @[src/main/core/Core.scala:26:21]
    .clock           (clock),
    .io_gpr_rs1_addr (_idu_io_gpr_rs1_addr),	// @[src/main/core/Core.scala:30:21]
    .io_gpr_rs2_addr (_idu_io_gpr_rs2_addr),	// @[src/main/core/Core.scala:30:21]
    .io_gpr_rs1_data (_gpr_io_gpr_rs1_data),
    .io_gpr_rs2_data (_gpr_io_gpr_rs2_data),
    .io_gpr_wen      (_wbu_io_gpr_wen),	// @[src/main/core/Core.scala:33:21]
    .io_gpr_addr     (_wbu_io_gpr_addr),	// @[src/main/core/Core.scala:33:21]
    .io_gpr_wdata    (_wbu_io_gpr_wdata)	// @[src/main/core/Core.scala:33:21]
  );
  CSR csr (	// @[src/main/core/Core.scala:27:21]
    .clock          (clock),
    .io_csr_mtvec   (_csr_io_csr_mtvec),
    .io_csr_mepc    (_csr_io_csr_mepc),
    .io_csr_rdata   (_csr_io_csr_rdata),
    .io_csr_wdata   (_wbu_io_csr_wdata),	// @[src/main/core/Core.scala:33:21]
    .io_csr_addr    (_wbu_io_csr_addr),	// @[src/main/core/Core.scala:33:21]
    .io_csr_cmd     (_wbu_io_csr_cmd),	// @[src/main/core/Core.scala:33:21]
    .io_csr_raddr   (_idu_io_csr_raddr),	// @[src/main/core/Core.scala:30:21]
    .io_csr_reg_pc  (wbu_io_pipe_in_bits_r_ls2wb_reg_pc),	// @[src/main/core/Core.scala:325:33]
    .io_csr_irq_num (_wbu_io_irq_num),	// @[src/main/core/Core.scala:33:21]
    .io_csr_is_irq  (is_irq)	// @[src/main/core/Core.scala:256:25]
  );
  IFU ifu (	// @[src/main/core/Core.scala:29:21]
    .clock                         (clock),
    .reset                         (reset),
    .io_imem_araddr                (_ifu_io_imem_araddr),
    .io_imem_arvalid               (_ifu_io_imem_arvalid),
    .io_imem_arready               (_icache_io_in_arready),	// @[src/main/core/Core.scala:59:24]
    .io_imem_rdata                 (_icache_io_in_rdata),	// @[src/main/core/Core.scala:59:24]
    .io_imem_rvalid                (_icache_io_in_rvalid),	// @[src/main/core/Core.scala:59:24]
    .io_imem_rready                (_ifu_io_imem_rready),
    .io_br_flg                     (_exu_io_br_flg),	// @[src/main/core/Core.scala:31:21]
    .io_jmp_flg                    (_exu_io_jmp_flg),	// @[src/main/core/Core.scala:31:21]
    .io_br_target                  (_exu_io_br_target),	// @[src/main/core/Core.scala:31:21]
    .io_alu_out                    (_exu_io_alu_out),	// @[src/main/core/Core.scala:31:21]
    .io_csr_mtvec                  (_csr_io_csr_mtvec),	// @[src/main/core/Core.scala:27:21]
    .io_csr_mepc                   (_csr_io_csr_mepc),	// @[src/main/core/Core.scala:27:21]
    .io_is_mret                    (_idu_io_is_mret),	// @[src/main/core/Core.scala:30:21]
    .io_pipe_in_ready              (_ifu_io_pipe_in_ready),
    .io_pipe_in_valid              (_GEN_2),	// @[src/main/core/Core.scala:42:26, :276:{34,56}]
    .io_pipe_out_ready             (_idu_io_pipe_in_ready),	// @[src/main/core/Core.scala:30:21]
    .io_pipe_out_valid             (_ifu_io_pipe_out_valid),
    .io_pipe_out_bits_if2id_reg_pc (_ifu_io_pipe_out_bits_if2id_reg_pc),
    .io_pipe_out_bits_if2id_inst   (_ifu_io_pipe_out_bits_if2id_inst),
    .io_hazard_flush_flg           (_exu_io_hazard_flush_flg_T)	// @[src/main/core/Core.scala:269:47]
  );
  IDU idu (	// @[src/main/core/Core.scala:30:21]
    .clock                                    (clock),
    .reset                                    (reset),
    .io_gpr_rs1_addr                          (_idu_io_gpr_rs1_addr),
    .io_gpr_rs2_addr                          (_idu_io_gpr_rs2_addr),
    .io_gpr_rs1_data                          (_gpr_io_gpr_rs1_data),	// @[src/main/core/Core.scala:26:21]
    .io_gpr_rs2_data                          (_gpr_io_gpr_rs2_data),	// @[src/main/core/Core.scala:26:21]
    .io_gpr_rs1_is_read                       (_idu_io_gpr_rs1_is_read),
    .io_gpr_rs2_is_read                       (_idu_io_gpr_rs2_is_read),
    .io_csr_raddr                             (_idu_io_csr_raddr),
    .io_csr_rdata                             (_csr_io_csr_rdata),	// @[src/main/core/Core.scala:27:21]
    .io_is_mret                               (_idu_io_is_mret),
    .io_pipe_in_ready                         (_idu_io_pipe_in_ready),
    .io_pipe_in_valid                         (_GEN_3),	// @[src/main/core/Core.scala:277:{34,56}, :326:22]
    .io_pipe_in_bits_if2id_reg_pc             (idu_io_pipe_in_bits_r_if2id_reg_pc),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_if2id_inst               (idu_io_pipe_in_bits_r_if2id_inst),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_out_ready                        (_exu_io_pipe_in_ready),	// @[src/main/core/Core.scala:31:21]
    .io_pipe_out_valid                        (_idu_io_pipe_out_valid),
    .io_pipe_out_bits_id2exe_reg_pc           (_idu_io_pipe_out_bits_id2exe_reg_pc),
    .io_pipe_out_bits_id2exe_op1_data         (_idu_io_pipe_out_bits_id2exe_op1_data),
    .io_pipe_out_bits_id2exe_op2_data         (_idu_io_pipe_out_bits_id2exe_op2_data),
    .io_pipe_out_bits_id2exe_rs2_data         (_idu_io_pipe_out_bits_id2exe_rs2_data),
    .io_pipe_out_bits_id2exe_wb_addr          (_idu_io_pipe_out_bits_id2exe_wb_addr),
    .io_pipe_out_bits_id2exe_rf_wen           (_idu_io_pipe_out_bits_id2exe_rf_wen),
    .io_pipe_out_bits_id2exe_exe_fun          (_idu_io_pipe_out_bits_id2exe_exe_fun),
    .io_pipe_out_bits_id2exe_wb_sel           (_idu_io_pipe_out_bits_id2exe_wb_sel),
    .io_pipe_out_bits_id2exe_imm_b_sext       (_idu_io_pipe_out_bits_id2exe_imm_b_sext),
    .io_pipe_out_bits_id2exe_csr_addr         (_idu_io_pipe_out_bits_id2exe_csr_addr),
    .io_pipe_out_bits_id2exe_csr_cmd          (_idu_io_pipe_out_bits_id2exe_csr_cmd),
    .io_pipe_out_bits_id2exe_mem_wen          (_idu_io_pipe_out_bits_id2exe_mem_wen),
    .io_pipe_out_bits_id2exe_mem_op           (_idu_io_pipe_out_bits_id2exe_mem_op),
    .io_pipe_out_bits_id2exe_is_irq           (_idu_io_pipe_out_bits_id2exe_is_irq),
    .io_pipe_out_bits_id2exe_irq_num          (_idu_io_pipe_out_bits_id2exe_irq_num),
    .io_pipe_out_bits_id2exe_csr_rdata        (_idu_io_pipe_out_bits_id2exe_csr_rdata),
    .fencei_io_vr_is_fencei_io_ready          (_icache_fencei_io_vr_is_fencei_io_ready),	// @[src/main/core/Core.scala:59:24]
    .fencei_io_vr_is_fencei_io_valid          (_idu_fencei_io_vr_is_fencei_io_valid),
    .fencei_io_vr_is_fencei_io_bits_is_fencei
      (_idu_fencei_io_vr_is_fencei_io_bits_is_fencei),
    .io_hazard_stall_flg                      (rs1_raw_valid | rs2_raw_valid | is_raw)	// @[src/main/core/Core.scala:142:37, :165:32, :166:32, :212:62]
  );
  EXU exu (	// @[src/main/core/Core.scala:31:21]
    .clock                             (clock),
    .reset                             (reset),
    .io_br_flg                         (_exu_io_br_flg),
    .io_jmp_flg                        (_exu_io_jmp_flg),
    .io_br_target                      (_exu_io_br_target),
    .io_alu_out                        (_exu_io_alu_out),
    .io_pipe_in_ready                  (_exu_io_pipe_in_ready),
    .io_pipe_in_valid                  (_GEN_1),	// @[src/main/core/Core.scala:278:{34,56}, :326:22]
    .io_pipe_in_bits_id2exe_reg_pc     (exu_io_pipe_in_bits_r_id2exe_reg_pc),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_op1_data   (exu_io_pipe_in_bits_r_id2exe_op1_data),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_op2_data   (exu_io_pipe_in_bits_r_id2exe_op2_data),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_rs2_data   (exu_io_pipe_in_bits_r_id2exe_rs2_data),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_wb_addr    (exu_io_pipe_in_bits_r_id2exe_wb_addr),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_rf_wen     (exu_io_pipe_in_bits_r_id2exe_rf_wen),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_exe_fun    (exu_io_pipe_in_bits_r_id2exe_exe_fun),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_wb_sel     (exu_io_pipe_in_bits_r_id2exe_wb_sel),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_imm_b_sext (exu_io_pipe_in_bits_r_id2exe_imm_b_sext),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_csr_addr   (exu_io_pipe_in_bits_r_id2exe_csr_addr),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_csr_cmd    (exu_io_pipe_in_bits_r_id2exe_csr_cmd),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_mem_wen    (exu_io_pipe_in_bits_r_id2exe_mem_wen),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_mem_op     (exu_io_pipe_in_bits_r_id2exe_mem_op),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_is_irq     (exu_io_pipe_in_bits_r_id2exe_is_irq),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_irq_num    (exu_io_pipe_in_bits_r_id2exe_irq_num),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_id2exe_csr_rdata  (exu_io_pipe_in_bits_r_id2exe_csr_rdata),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_out_ready                 (_lsu_io_pipe_in_ready),	// @[src/main/core/Core.scala:32:21]
    .io_pipe_out_valid                 (_exu_io_pipe_out_valid),
    .io_pipe_out_bits_exe2ls_reg_pc    (_exu_io_pipe_out_bits_exe2ls_reg_pc),
    .io_pipe_out_bits_exe2ls_op1_data  (_exu_io_pipe_out_bits_exe2ls_op1_data),
    .io_pipe_out_bits_exe2ls_rs2_data  (_exu_io_pipe_out_bits_exe2ls_rs2_data),
    .io_pipe_out_bits_exe2ls_wb_addr   (_exu_io_pipe_out_bits_exe2ls_wb_addr),
    .io_pipe_out_bits_exe2ls_alu_out   (_exu_io_pipe_out_bits_exe2ls_alu_out),
    .io_pipe_out_bits_exe2ls_rf_wen    (_exu_io_pipe_out_bits_exe2ls_rf_wen),
    .io_pipe_out_bits_exe2ls_wb_sel    (_exu_io_pipe_out_bits_exe2ls_wb_sel),
    .io_pipe_out_bits_exe2ls_csr_addr  (_exu_io_pipe_out_bits_exe2ls_csr_addr),
    .io_pipe_out_bits_exe2ls_csr_cmd   (_exu_io_pipe_out_bits_exe2ls_csr_cmd),
    .io_pipe_out_bits_exe2ls_mem_wen   (_exu_io_pipe_out_bits_exe2ls_mem_wen),
    .io_pipe_out_bits_exe2ls_mem_op    (_exu_io_pipe_out_bits_exe2ls_mem_op),
    .io_pipe_out_bits_exe2ls_is_irq    (_exu_io_pipe_out_bits_exe2ls_is_irq),
    .io_pipe_out_bits_exe2ls_irq_num   (_exu_io_pipe_out_bits_exe2ls_irq_num),
    .io_pipe_out_bits_exe2ls_csr_rdata (_exu_io_pipe_out_bits_exe2ls_csr_rdata)
  );
  LSU lsu (	// @[src/main/core/Core.scala:32:21]
    .clock                            (clock),
    .reset                            (reset),
    .io_dmem_araddr                   (io_dmem_araddr),
    .io_dmem_arvalid                  (io_dmem_arvalid),
    .io_dmem_arready                  (io_dmem_arready),
    .io_dmem_arsize                   (io_dmem_arsize),
    .io_dmem_rdata                    (io_dmem_rdata),
    .io_dmem_rresp                    (io_dmem_rresp),
    .io_dmem_rvalid                   (io_dmem_rvalid),
    .io_dmem_rready                   (io_dmem_rready),
    .io_dmem_awaddr                   (io_dmem_awaddr),
    .io_dmem_awvalid                  (io_dmem_awvalid),
    .io_dmem_awready                  (io_dmem_awready),
    .io_dmem_awsize                   (io_dmem_awsize),
    .io_dmem_wdata                    (io_dmem_wdata),
    .io_dmem_wstrb                    (io_dmem_wstrb),
    .io_dmem_wvalid                   (io_dmem_wvalid),
    .io_dmem_wready                   (io_dmem_wready),
    .io_dmem_bresp                    (io_dmem_bresp),
    .io_dmem_bvalid                   (io_dmem_bvalid),
    .io_dmem_bready                   (io_dmem_bready),
    .io_pipe_in_ready                 (_lsu_io_pipe_in_ready),
    .io_pipe_in_valid                 (_GEN_0),	// @[src/main/core/Core.scala:279:{34,56}, :326:22]
    .io_pipe_in_bits_exe2ls_reg_pc    (lsu_io_pipe_in_bits_r_exe2ls_reg_pc),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_op1_data  (lsu_io_pipe_in_bits_r_exe2ls_op1_data),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_rs2_data  (lsu_io_pipe_in_bits_r_exe2ls_rs2_data),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_wb_addr   (lsu_io_pipe_in_bits_r_exe2ls_wb_addr),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_alu_out   (lsu_io_pipe_in_bits_r_exe2ls_alu_out),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_rf_wen    (lsu_io_pipe_in_bits_r_exe2ls_rf_wen),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_wb_sel    (lsu_io_pipe_in_bits_r_exe2ls_wb_sel),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_csr_addr  (lsu_io_pipe_in_bits_r_exe2ls_csr_addr),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_csr_cmd   (lsu_io_pipe_in_bits_r_exe2ls_csr_cmd),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_mem_wen   (lsu_io_pipe_in_bits_r_exe2ls_mem_wen),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_mem_op    (lsu_io_pipe_in_bits_r_exe2ls_mem_op),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_is_irq    (lsu_io_pipe_in_bits_r_exe2ls_is_irq),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_irq_num   (lsu_io_pipe_in_bits_r_exe2ls_irq_num),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_exe2ls_csr_rdata (lsu_io_pipe_in_bits_r_exe2ls_csr_rdata),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_out_ready                (_wbu_io_pipe_in_ready),	// @[src/main/core/Core.scala:33:21]
    .io_pipe_out_valid                (_lsu_io_pipe_out_valid),
    .io_pipe_out_bits_ls2wb_reg_pc    (_lsu_io_pipe_out_bits_ls2wb_reg_pc),
    .io_pipe_out_bits_ls2wb_wb_addr   (_lsu_io_pipe_out_bits_ls2wb_wb_addr),
    .io_pipe_out_bits_ls2wb_rf_wen    (_lsu_io_pipe_out_bits_ls2wb_rf_wen),
    .io_pipe_out_bits_ls2wb_wb_data   (_lsu_io_pipe_out_bits_ls2wb_wb_data),
    .io_pipe_out_bits_ls2wb_csr_wdata (_lsu_io_pipe_out_bits_ls2wb_csr_wdata),
    .io_pipe_out_bits_ls2wb_csr_addr  (_lsu_io_pipe_out_bits_ls2wb_csr_addr),
    .io_pipe_out_bits_ls2wb_csr_cmd   (_lsu_io_pipe_out_bits_ls2wb_csr_cmd),
    .io_pipe_out_bits_ls2wb_is_irq    (_lsu_io_pipe_out_bits_ls2wb_is_irq),
    .io_pipe_out_bits_ls2wb_irq_num   (_lsu_io_pipe_out_bits_ls2wb_irq_num),
    .io_hazard_flush_flg              (is_irq)	// @[src/main/core/Core.scala:256:25]
  );
  WBU wbu (	// @[src/main/core/Core.scala:33:21]
    .clock                           (clock),
    .reset                           (reset),
    .io_gpr_wen                      (_wbu_io_gpr_wen),
    .io_gpr_addr                     (_wbu_io_gpr_addr),
    .io_gpr_wdata                    (_wbu_io_gpr_wdata),
    .io_csr_addr                     (_wbu_io_csr_addr),
    .io_csr_cmd                      (_wbu_io_csr_cmd),
    .io_csr_wdata                    (_wbu_io_csr_wdata),
    .io_is_irq                       (_wbu_io_is_irq),
    .io_irq_num                      (_wbu_io_irq_num),
    .io_irq_valid                    (_wbu_io_irq_valid),
    .io_pipe_in_ready                (_wbu_io_pipe_in_ready),
    .io_pipe_in_valid                (_GEN),	// @[src/main/core/Core.scala:280:{34,56}, :326:22]
    .io_pipe_in_bits_ls2wb_reg_pc    (wbu_io_pipe_in_bits_r_ls2wb_reg_pc),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_ls2wb_wb_addr   (wbu_io_pipe_in_bits_r_ls2wb_wb_addr),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_ls2wb_rf_wen    (wbu_io_pipe_in_bits_r_ls2wb_rf_wen),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_ls2wb_wb_data   (wbu_io_pipe_in_bits_r_ls2wb_wb_data),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_ls2wb_csr_wdata (wbu_io_pipe_in_bits_r_ls2wb_csr_wdata),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_ls2wb_csr_addr  (wbu_io_pipe_in_bits_r_ls2wb_csr_addr),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_ls2wb_csr_cmd   (wbu_io_pipe_in_bits_r_ls2wb_csr_cmd),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_ls2wb_is_irq    (wbu_io_pipe_in_bits_r_ls2wb_is_irq),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_in_bits_ls2wb_irq_num   (wbu_io_pipe_in_bits_r_ls2wb_irq_num),	// @[src/main/core/Core.scala:325:33]
    .io_pipe_out_ready               (1'h1),	// @[src/main/core/Core.scala:40:27]
    .io_pipe_out_valid               (/* unused */),
    .io_hazard_flush_flg             (is_irq)	// @[src/main/core/Core.scala:256:25]
  );
  iCache icache (	// @[src/main/core/Core.scala:59:24]
    .clock                                    (clock),
    .reset                                    (reset),
    .io_in_araddr                             (_ifu_io_imem_araddr),	// @[src/main/core/Core.scala:29:21]
    .io_in_arvalid                            (_ifu_io_imem_arvalid),	// @[src/main/core/Core.scala:29:21]
    .io_in_arready                            (_icache_io_in_arready),
    .io_in_rdata                              (_icache_io_in_rdata),
    .io_in_rvalid                             (_icache_io_in_rvalid),
    .io_in_rready                             (_ifu_io_imem_rready),	// @[src/main/core/Core.scala:29:21]
    .io_out_araddr                            (io_imem_araddr),
    .io_out_arvalid                           (io_imem_arvalid),
    .io_out_arready                           (io_imem_arready),
    .io_out_arid                              (io_imem_arid),
    .io_out_arlen                             (io_imem_arlen),
    .io_out_arsize                            (io_imem_arsize),
    .io_out_arburst                           (io_imem_arburst),
    .io_out_rdata                             (io_imem_rdata),
    .io_out_rvalid                            (io_imem_rvalid),
    .io_out_rready                            (io_imem_rready),
    .io_out_awaddr                            (io_imem_awaddr),
    .io_out_awvalid                           (io_imem_awvalid),
    .io_out_awid                              (io_imem_awid),
    .io_out_awlen                             (io_imem_awlen),
    .io_out_awsize                            (io_imem_awsize),
    .io_out_awburst                           (io_imem_awburst),
    .io_out_wdata                             (io_imem_wdata),
    .io_out_wstrb                             (io_imem_wstrb),
    .io_out_wvalid                            (io_imem_wvalid),
    .io_out_wlast                             (io_imem_wlast),
    .io_out_bready                            (io_imem_bready),
    .fencei_io_vr_is_fencei_io_ready          (_icache_fencei_io_vr_is_fencei_io_ready),
    .fencei_io_vr_is_fencei_io_valid          (_idu_fencei_io_vr_is_fencei_io_valid),	// @[src/main/core/Core.scala:30:21]
    .fencei_io_vr_is_fencei_io_bits_is_fencei
      (_idu_fencei_io_vr_is_fencei_io_bits_is_fencei)	// @[src/main/core/Core.scala:30:21]
  );
endmodule

