// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module EXU(	// @[src/main/core/exu/EXU.scala:66:7]
  input         clock,	// @[src/main/core/exu/EXU.scala:66:7]
                reset,	// @[src/main/core/exu/EXU.scala:66:7]
  output [31:0] io_dmem_araddr,	// @[src/main/core/exu/EXU.scala:67:16]
  output        io_dmem_arvalid,	// @[src/main/core/exu/EXU.scala:67:16]
  input         io_dmem_arready,	// @[src/main/core/exu/EXU.scala:67:16]
  output [2:0]  io_dmem_arsize,	// @[src/main/core/exu/EXU.scala:67:16]
  input  [31:0] io_dmem_rdata,	// @[src/main/core/exu/EXU.scala:67:16]
  input         io_dmem_rvalid,	// @[src/main/core/exu/EXU.scala:67:16]
  output        io_dmem_rready,	// @[src/main/core/exu/EXU.scala:67:16]
  output [31:0] io_dmem_awaddr,	// @[src/main/core/exu/EXU.scala:67:16]
  output        io_dmem_awvalid,	// @[src/main/core/exu/EXU.scala:67:16]
  input         io_dmem_awready,	// @[src/main/core/exu/EXU.scala:67:16]
  output [2:0]  io_dmem_awsize,	// @[src/main/core/exu/EXU.scala:67:16]
  output [31:0] io_dmem_wdata,	// @[src/main/core/exu/EXU.scala:67:16]
  output [3:0]  io_dmem_wstrb,	// @[src/main/core/exu/EXU.scala:67:16]
  output        io_dmem_wvalid,	// @[src/main/core/exu/EXU.scala:67:16]
  input         io_dmem_wready,	// @[src/main/core/exu/EXU.scala:67:16]
                io_dmem_bvalid,	// @[src/main/core/exu/EXU.scala:67:16]
  output        io_dmem_bready,	// @[src/main/core/exu/EXU.scala:67:16]
                io_bj_valid,	// @[src/main/core/exu/EXU.scala:68:19]
  output [31:0] io_bj_target,	// @[src/main/core/exu/EXU.scala:68:19]
  output        io_pipe_in_ready,	// @[src/main/core/exu/EXU.scala:69:21]
  input         io_pipe_in_valid,	// @[src/main/core/exu/EXU.scala:69:21]
  input  [1:0]  io_pipe_in_bits_is2exe_processunit,	// @[src/main/core/exu/EXU.scala:69:21]
  input  [3:0]  io_pipe_in_bits_is2exe_processtpe,	// @[src/main/core/exu/EXU.scala:69:21]
                io_pipe_in_bits_is2exe_bjtpe,	// @[src/main/core/exu/EXU.scala:69:21]
  input         io_pipe_in_bits_is2exe_rfwe,	// @[src/main/core/exu/EXU.scala:69:21]
  input  [3:0]  io_pipe_in_bits_is2exe_rd_addr,	// @[src/main/core/exu/EXU.scala:69:21]
  input  [31:0] io_pipe_in_bits_is2exe_ch1,	// @[src/main/core/exu/EXU.scala:69:21]
                io_pipe_in_bits_is2exe_ch2,	// @[src/main/core/exu/EXU.scala:69:21]
                io_pipe_in_bits_is2exe_ch3,	// @[src/main/core/exu/EXU.scala:69:21]
  input         io_pipe_out_ready,	// @[src/main/core/exu/EXU.scala:69:21]
  output        io_pipe_out_valid,	// @[src/main/core/exu/EXU.scala:69:21]
                io_pipe_out_bits_exe2wb_gpr_we,	// @[src/main/core/exu/EXU.scala:69:21]
  output [31:0] io_pipe_out_bits_exe2wb_gpr_wdata,	// @[src/main/core/exu/EXU.scala:69:21]
  output [3:0]  io_pipe_out_bits_exe2wb_gpr_waddr,	// @[src/main/core/exu/EXU.scala:69:21]
  output        io_for_valid,	// @[src/main/core/exu/EXU.scala:70:20]
  output [1:0]  io_for_processunit,	// @[src/main/core/exu/EXU.scala:70:20]
  output        io_for_gpr_we,	// @[src/main/core/exu/EXU.scala:70:20]
  output [31:0] io_for_gpr_wdata,	// @[src/main/core/exu/EXU.scala:70:20]
  output [3:0]  io_for_gpr_waddr,	// @[src/main/core/exu/EXU.scala:70:20]
  output        io_fencei_is_fencei,	// @[src/main/core/exu/EXU.scala:71:23]
  input         io_fencei_fencei_done,	// @[src/main/core/exu/EXU.scala:71:23]
  output [31:0] io_fencei_flush_exu_fencei_flush_target	// @[src/main/core/exu/EXU.scala:72:33]
);

  reg         in_ready;	// @[src/main/core/exu/EXU.scala:163:27]
  wire        _lsu_io_in_ready;	// @[src/main/core/exu/EXU.scala:116:21]
  wire        _lsu_io_out_valid;	// @[src/main/core/exu/EXU.scala:116:21]
  wire [31:0] _lsu_io_out_bits_gpr_wdata;	// @[src/main/core/exu/EXU.scala:116:21]
  wire        _alu_io_in_ready;	// @[src/main/core/exu/EXU.scala:102:21]
  wire        _alu_io_out_valid;	// @[src/main/core/exu/EXU.scala:102:21]
  wire [31:0] _alu_io_out_bits_alu_out;	// @[src/main/core/exu/EXU.scala:102:21]
  wire        _alu_io_bj_valid;	// @[src/main/core/exu/EXU.scala:102:21]
  wire        _csr_io_out_valid;	// @[src/main/core/exu/EXU.scala:89:21]
  wire [31:0] _csr_io_out_bits_csr_rdata;	// @[src/main/core/exu/EXU.scala:89:21]
  wire        _csr_io_bj_valid;	// @[src/main/core/exu/EXU.scala:89:21]
  wire [31:0] _csr_io_bj_target;	// @[src/main/core/exu/EXU.scala:89:21]
  wire        _n_state_T_1 = in_ready & io_pipe_in_valid;	// @[src/main/core/exu/EXU.scala:163:27, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _gpr_wdata_T = io_pipe_in_bits_is2exe_processunit == 2'h1;	// @[src/main/core/exu/EXU.scala:90:55]
  wire        _gpr_wdata_T_1 = io_pipe_in_bits_is2exe_processunit == 2'h2;	// @[src/main/core/exu/EXU.scala:117:55]
  wire        exefsh =
    _csr_io_out_valid | _alu_io_out_valid | _lsu_io_out_valid | io_fencei_fencei_done;	// @[src/main/core/exu/EXU.scala:89:21, :102:21, :116:21, :142:73]
  wire [31:0] gpr_wdata =
    _gpr_wdata_T
      ? _csr_io_out_bits_csr_rdata
      : _gpr_wdata_T_1 ? _lsu_io_out_bits_gpr_wdata : _alu_io_out_bits_alu_out;	// @[src/main/core/exu/EXU.scala:89:21, :90:55, :102:21, :116:21, :117:55, :143:{24,88}]
  reg         out_valid;	// @[src/main/core/exu/EXU.scala:164:28]
  reg         c_state;	// @[src/main/core/exu/EXU.scala:169:26]
  wire        n_state = c_state ? ~(io_pipe_out_ready & out_valid) : _n_state_T_1;	// @[src/main/core/exu/EXU.scala:140:50, :164:28, :169:26, :170:30, :175:51, :176:33, :177:33, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[src/main/core/exu/EXU.scala:66:7]
    if (reset) begin	// @[src/main/core/exu/EXU.scala:66:7]
      in_ready <= 1'h0;	// @[src/main/core/exu/EXU.scala:66:7, :163:27]
      out_valid <= 1'h0;	// @[src/main/core/exu/EXU.scala:66:7, :164:28]
      c_state <= 1'h0;	// @[src/main/core/exu/EXU.scala:66:7, :169:26]
    end
    else begin	// @[src/main/core/exu/EXU.scala:66:7]
      if (n_state)	// @[src/main/core/exu/EXU.scala:170:30]
        in_ready <= ~n_state & in_ready;	// @[src/main/core/exu/EXU.scala:163:27, :170:30, :180:20, :186:22]
      else	// @[src/main/core/exu/EXU.scala:170:30]
        in_ready <= _alu_io_in_ready & _lsu_io_in_ready;	// @[src/main/core/exu/EXU.scala:102:21, :116:21, :163:27, :182:60]
      out_valid <= n_state & (n_state ? exefsh : out_valid);	// @[src/main/core/exu/EXU.scala:142:73, :164:28, :170:30, :180:20, :183:23, :187:23]
      c_state <= n_state;	// @[src/main/core/exu/EXU.scala:169:26, :170:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/exu/EXU.scala:66:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/exu/EXU.scala:66:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/exu/EXU.scala:66:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/core/exu/EXU.scala:66:7]
    initial begin	// @[src/main/core/exu/EXU.scala:66:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/exu/EXU.scala:66:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/exu/EXU.scala:66:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/exu/EXU.scala:66:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/core/exu/EXU.scala:66:7]
        in_ready = _RANDOM[/*Zero width*/ 1'b0][0];	// @[src/main/core/exu/EXU.scala:66:7, :163:27]
        out_valid = _RANDOM[/*Zero width*/ 1'b0][1];	// @[src/main/core/exu/EXU.scala:66:7, :163:27, :164:28]
        c_state = _RANDOM[/*Zero width*/ 1'b0][2];	// @[src/main/core/exu/EXU.scala:66:7, :163:27, :169:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/exu/EXU.scala:66:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/exu/EXU.scala:66:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CSR csr (	// @[src/main/core/exu/EXU.scala:89:21]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_valid           (_n_state_T_1 & _gpr_wdata_T),	// @[src/main/core/exu/EXU.scala:90:{40,55}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_in_bits_op1        (io_pipe_in_bits_is2exe_ch1),
    .io_in_bits_op2        (io_pipe_in_bits_is2exe_ch2),
    .io_in_bits_processtpe (io_pipe_in_bits_is2exe_processtpe),
    .io_out_valid          (_csr_io_out_valid),
    .io_out_bits_csr_rdata (_csr_io_out_bits_csr_rdata),
    .io_bj_valid           (_csr_io_bj_valid),
    .io_bj_target          (_csr_io_bj_target)
  );
  ALU alu (	// @[src/main/core/exu/EXU.scala:102:21]
    .io_in_ready           (_alu_io_in_ready),
    .io_in_valid
      (_n_state_T_1
       & (io_pipe_in_bits_is2exe_processunit == 2'h0
          | (&io_pipe_in_bits_is2exe_processunit))),	// @[src/main/core/exu/EXU.scala:103:{40,56,76,91}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_in_bits_op1        (io_pipe_in_bits_is2exe_ch1),
    .io_in_bits_op2        (io_pipe_in_bits_is2exe_ch2),
    .io_in_bits_processtpe (io_pipe_in_bits_is2exe_processtpe),
    .io_in_bits_bjtpe      (io_pipe_in_bits_is2exe_bjtpe),
    .io_out_ready          (io_pipe_out_ready),
    .io_out_valid          (_alu_io_out_valid),
    .io_out_bits_alu_out   (_alu_io_out_bits_alu_out),
    .io_bj_valid           (_alu_io_bj_valid)
  );
  LSU lsu (	// @[src/main/core/exu/EXU.scala:116:21]
    .clock                 (clock),
    .reset                 (reset),
    .io_dmem_dmem_araddr   (io_dmem_araddr),
    .io_dmem_dmem_arvalid  (io_dmem_arvalid),
    .io_dmem_dmem_arready  (io_dmem_arready),
    .io_dmem_dmem_arsize   (io_dmem_arsize),
    .io_dmem_dmem_rdata    (io_dmem_rdata),
    .io_dmem_dmem_rvalid   (io_dmem_rvalid),
    .io_dmem_dmem_rready   (io_dmem_rready),
    .io_dmem_dmem_awaddr   (io_dmem_awaddr),
    .io_dmem_dmem_awvalid  (io_dmem_awvalid),
    .io_dmem_dmem_awready  (io_dmem_awready),
    .io_dmem_dmem_awsize   (io_dmem_awsize),
    .io_dmem_dmem_wdata    (io_dmem_wdata),
    .io_dmem_dmem_wstrb    (io_dmem_wstrb),
    .io_dmem_dmem_wvalid   (io_dmem_wvalid),
    .io_dmem_dmem_wready   (io_dmem_wready),
    .io_dmem_dmem_bvalid   (io_dmem_bvalid),
    .io_dmem_dmem_bready   (io_dmem_bready),
    .io_in_ready           (_lsu_io_in_ready),
    .io_in_valid           (_n_state_T_1 & _gpr_wdata_T_1),	// @[src/main/core/exu/EXU.scala:117:{40,55}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_in_bits_op1        (io_pipe_in_bits_is2exe_ch3),
    .io_in_bits_op2        (io_pipe_in_bits_is2exe_ch2),
    .io_in_bits_processtpe (io_pipe_in_bits_is2exe_processtpe),
    .io_out_ready          (io_pipe_out_ready),
    .io_out_valid          (_lsu_io_out_valid),
    .io_out_bits_gpr_wdata (_lsu_io_out_bits_gpr_wdata)
  );
  assign io_bj_valid = _alu_io_bj_valid | _csr_io_bj_valid;	// @[src/main/core/exu/EXU.scala:66:7, :89:21, :102:21, :139:36]
  assign io_bj_target =
    _alu_io_bj_valid
      ? io_pipe_in_bits_is2exe_ch3
      : _csr_io_bj_valid ? _csr_io_bj_target : 32'h0;	// @[src/main/core/exu/EXU.scala:66:7, :89:21, :102:21, :140:{24,50}]
  assign io_pipe_in_ready = in_ready;	// @[src/main/core/exu/EXU.scala:66:7, :163:27]
  assign io_pipe_out_valid = out_valid;	// @[src/main/core/exu/EXU.scala:66:7, :164:28]
  assign io_pipe_out_bits_exe2wb_gpr_we = io_pipe_in_bits_is2exe_rfwe;	// @[src/main/core/exu/EXU.scala:66:7]
  assign io_pipe_out_bits_exe2wb_gpr_wdata = gpr_wdata;	// @[src/main/core/exu/EXU.scala:66:7, :143:24]
  assign io_pipe_out_bits_exe2wb_gpr_waddr = io_pipe_in_bits_is2exe_rd_addr;	// @[src/main/core/exu/EXU.scala:66:7]
  assign io_for_valid = exefsh;	// @[src/main/core/exu/EXU.scala:66:7, :142:73]
  assign io_for_processunit = io_pipe_in_bits_is2exe_processunit;	// @[src/main/core/exu/EXU.scala:66:7]
  assign io_for_gpr_we = io_pipe_in_bits_is2exe_rfwe;	// @[src/main/core/exu/EXU.scala:66:7]
  assign io_for_gpr_wdata = gpr_wdata;	// @[src/main/core/exu/EXU.scala:66:7, :143:24]
  assign io_for_gpr_waddr = io_pipe_in_bits_is2exe_rd_addr;	// @[src/main/core/exu/EXU.scala:66:7]
  assign io_fencei_is_fencei = _n_state_T_1 & (&io_pipe_in_bits_is2exe_processunit);	// @[src/main/core/exu/EXU.scala:66:7, :103:91, :130:44, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign io_fencei_flush_exu_fencei_flush_target = _alu_io_out_bits_alu_out;	// @[src/main/core/exu/EXU.scala:66:7, :102:21]
endmodule

