// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module EXU(	// @[src/main/core/exu/EXU.scala:49:7]
  input         clock,	// @[src/main/core/exu/EXU.scala:49:7]
                reset,	// @[src/main/core/exu/EXU.scala:49:7]
  output        io_br_flg,	// @[src/main/core/exu/EXU.scala:50:16]
                io_jmp_flg,	// @[src/main/core/exu/EXU.scala:50:16]
  output [31:0] io_br_target,	// @[src/main/core/exu/EXU.scala:50:16]
                io_alu_out,	// @[src/main/core/exu/EXU.scala:50:16]
  output        io_pipe_in_ready,	// @[src/main/core/exu/EXU.scala:51:21]
  input         io_pipe_in_valid,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [31:0] io_pipe_in_bits_id2exe_reg_pc,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [1:0]  io_pipe_in_bits_id2exe_op1_sel,	// @[src/main/core/exu/EXU.scala:51:21]
                io_pipe_in_bits_id2exe_op2_sel,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [31:0] io_pipe_in_bits_id2exe_rs1_data,	// @[src/main/core/exu/EXU.scala:51:21]
                io_pipe_in_bits_id2exe_rs2_data,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [3:0]  io_pipe_in_bits_id2exe_wb_addr,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [1:0]  io_pipe_in_bits_id2exe_rf_wen,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [4:0]  io_pipe_in_bits_id2exe_exe_fun,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [2:0]  io_pipe_in_bits_id2exe_wb_sel,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [31:0] io_pipe_in_bits_id2exe_imm_sext,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [11:0] io_pipe_in_bits_id2exe_csr_addr,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [2:0]  io_pipe_in_bits_id2exe_csr_cmd,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [1:0]  io_pipe_in_bits_id2exe_mem_wen,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [2:0]  io_pipe_in_bits_id2exe_mem_op,	// @[src/main/core/exu/EXU.scala:51:21]
  input         io_pipe_in_bits_id2exe_is_irq,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [3:0]  io_pipe_in_bits_id2exe_irq_num,	// @[src/main/core/exu/EXU.scala:51:21]
  input  [31:0] io_pipe_in_bits_id2exe_csr_rdata,	// @[src/main/core/exu/EXU.scala:51:21]
  input         io_pipe_out_ready,	// @[src/main/core/exu/EXU.scala:51:21]
  output        io_pipe_out_valid,	// @[src/main/core/exu/EXU.scala:51:21]
  output [31:0] io_pipe_out_bits_exe2ls_reg_pc,	// @[src/main/core/exu/EXU.scala:51:21]
                io_pipe_out_bits_exe2ls_op1_data,	// @[src/main/core/exu/EXU.scala:51:21]
                io_pipe_out_bits_exe2ls_rs2_data,	// @[src/main/core/exu/EXU.scala:51:21]
  output [3:0]  io_pipe_out_bits_exe2ls_wb_addr,	// @[src/main/core/exu/EXU.scala:51:21]
  output [31:0] io_pipe_out_bits_exe2ls_alu_out,	// @[src/main/core/exu/EXU.scala:51:21]
  output [1:0]  io_pipe_out_bits_exe2ls_rf_wen,	// @[src/main/core/exu/EXU.scala:51:21]
  output [2:0]  io_pipe_out_bits_exe2ls_wb_sel,	// @[src/main/core/exu/EXU.scala:51:21]
  output [11:0] io_pipe_out_bits_exe2ls_csr_addr,	// @[src/main/core/exu/EXU.scala:51:21]
  output [2:0]  io_pipe_out_bits_exe2ls_csr_cmd,	// @[src/main/core/exu/EXU.scala:51:21]
  output [1:0]  io_pipe_out_bits_exe2ls_mem_wen,	// @[src/main/core/exu/EXU.scala:51:21]
  output [2:0]  io_pipe_out_bits_exe2ls_mem_op,	// @[src/main/core/exu/EXU.scala:51:21]
  output        io_pipe_out_bits_exe2ls_is_irq,	// @[src/main/core/exu/EXU.scala:51:21]
  output [3:0]  io_pipe_out_bits_exe2ls_irq_num,	// @[src/main/core/exu/EXU.scala:51:21]
  output [31:0] io_pipe_out_bits_exe2ls_csr_rdata,	// @[src/main/core/exu/EXU.scala:51:21]
  input         io_hazard_flush_flg	// @[src/main/core/exu/EXU.scala:54:23]
);

  wire [31:0] op1_data =
    io_pipe_in_bits_id2exe_op1_sel == 2'h0
      ? io_pipe_in_bits_id2exe_rs1_data
      : io_pipe_in_bits_id2exe_op1_sel == 2'h1 ? io_pipe_in_bits_id2exe_reg_pc : 32'h0;	// @[src/main/core/exu/EXU.scala:65:41, :66:41, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [31:0] op2_data =
    io_pipe_in_bits_id2exe_op2_sel == 2'h1
      ? io_pipe_in_bits_id2exe_rs2_data
      : io_pipe_in_bits_id2exe_imm_sext;	// @[src/main/core/exu/EXU.scala:66:41, :70:{23,55}]
  wire        _alu_out_T_1 = io_pipe_in_bits_id2exe_exe_fun == 5'h2;	// @[src/main/core/exu/EXU.scala:74:64]
  wire [31:0] _adder_func_T_4 =
    op1_data + ({32{_alu_out_T_1}} ^ op2_data) + {31'h0, _alu_out_T_1};	// @[src/main/core/exu/EXU.scala:70:23, :74:{32,64}, :75:51, :89:69, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        lts = $signed(op1_data) < $signed(op2_data);	// @[src/main/core/exu/EXU.scala:70:23, :78:31, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        ltu = op1_data < op2_data;	// @[src/main/core/exu/EXU.scala:70:23, :79:24, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        eq = op1_data == op2_data;	// @[src/main/core/exu/EXU.scala:70:23, :80:23, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [62:0] _alu_out_T_10 = {31'h0, op1_data} << op2_data[4:0];	// @[src/main/core/exu/EXU.scala:70:23, :89:{69,80}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [31:0] _GEN = {27'h0, op2_data[4:0]};	// @[src/main/core/exu/EXU.scala:70:23, :89:80, :90:69]
  wire [31:0] alu_out =
    io_pipe_in_bits_id2exe_exe_fun == 5'h1 | _alu_out_T_1
      ? _adder_func_T_4
      : io_pipe_in_bits_id2exe_exe_fun == 5'h3
          ? op1_data & op2_data
          : io_pipe_in_bits_id2exe_exe_fun == 5'h4
              ? op1_data | op2_data
              : io_pipe_in_bits_id2exe_exe_fun == 5'h5
                  ? op1_data ^ op2_data
                  : io_pipe_in_bits_id2exe_exe_fun == 5'h6
                      ? _alu_out_T_10[31:0]
                      : io_pipe_in_bits_id2exe_exe_fun == 5'h7
                          ? op1_data >> _GEN
                          : io_pipe_in_bits_id2exe_exe_fun == 5'h8
                              ? $signed($signed(op1_data) >>> _GEN)
                              : io_pipe_in_bits_id2exe_exe_fun == 5'h9
                                  ? {31'h0, lts}
                                  : io_pipe_in_bits_id2exe_exe_fun == 5'hA
                                      ? {31'h0, ltu}
                                      : io_pipe_in_bits_id2exe_exe_fun == 5'h11
                                          ? _adder_func_T_4 & 32'hFFFFFFFE
                                          : io_pipe_in_bits_id2exe_exe_fun == 5'h12
                                              ? op1_data
                                              : 32'h0;	// @[src/main/core/exu/EXU.scala:70:23, :74:64, :75:51, :78:31, :79:24, :84:41, :86:{41,69}, :87:{41,69}, :88:{41,69}, :89:{41,69,87}, :90:{41,69}, :91:{41,76}, :92:41, :93:41, :94:{41,73,75}, :95:41, src/main/scala/chisel3/util/Mux.scala:126:16]
  reg         in_ready;	// @[src/main/core/exu/EXU.scala:151:27]
  reg         out_valid;	// @[src/main/core/exu/EXU.scala:152:28]
  wire        io_pipe_out_valid_0 = out_valid & ~io_hazard_flush_flg;	// @[src/main/core/exu/EXU.scala:152:28, :154:{36,38}]
  reg         c_state;	// @[src/main/core/exu/EXU.scala:157:26]
  wire        n_state =
    c_state
      ? ~(io_pipe_out_ready & io_pipe_out_valid_0 | io_hazard_flush_flg)
      : in_ready & io_pipe_in_valid & ~io_hazard_flush_flg;	// @[src/main/core/exu/EXU.scala:75:56, :151:27, :154:{36,38}, :157:26, :158:30, :163:51, :164:50, :165:{33,51}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[src/main/core/exu/EXU.scala:49:7]
    if (reset) begin	// @[src/main/core/exu/EXU.scala:49:7]
      in_ready <= 1'h0;	// @[src/main/core/exu/EXU.scala:49:7, :151:27]
      out_valid <= 1'h0;	// @[src/main/core/exu/EXU.scala:49:7, :152:28]
      c_state <= 1'h0;	// @[src/main/core/exu/EXU.scala:49:7, :157:26]
    end
    else begin	// @[src/main/core/exu/EXU.scala:49:7]
      in_ready <= ~n_state | ~n_state & in_ready;	// @[src/main/core/exu/EXU.scala:151:27, :158:30, :168:20, :170:22, :174:22]
      out_valid <= n_state & (n_state | out_valid);	// @[src/main/core/exu/EXU.scala:152:28, :158:30, :168:20, :171:23, :175:23]
      c_state <= n_state;	// @[src/main/core/exu/EXU.scala:157:26, :158:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/exu/EXU.scala:49:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/exu/EXU.scala:49:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/exu/EXU.scala:49:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/core/exu/EXU.scala:49:7]
    initial begin	// @[src/main/core/exu/EXU.scala:49:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/exu/EXU.scala:49:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/exu/EXU.scala:49:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/exu/EXU.scala:49:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/core/exu/EXU.scala:49:7]
        in_ready = _RANDOM[/*Zero width*/ 1'b0][0];	// @[src/main/core/exu/EXU.scala:49:7, :151:27]
        out_valid = _RANDOM[/*Zero width*/ 1'b0][1];	// @[src/main/core/exu/EXU.scala:49:7, :151:27, :152:28]
        c_state = _RANDOM[/*Zero width*/ 1'b0][2];	// @[src/main/core/exu/EXU.scala:49:7, :151:27, :157:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/exu/EXU.scala:49:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/exu/EXU.scala:49:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_br_flg =
    (io_pipe_in_bits_id2exe_exe_fun == 5'hB)
      ? eq
      : io_pipe_in_bits_id2exe_exe_fun == 5'hC
          ? ~eq
          : (io_pipe_in_bits_id2exe_exe_fun == 5'hD)
              ? lts
              : io_pipe_in_bits_id2exe_exe_fun == 5'hE
                  ? ~lts
                  : io_pipe_in_bits_id2exe_exe_fun == 5'hF
                      ? ltu
                      : io_pipe_in_bits_id2exe_exe_fun == 5'h10 & ~ltu;	// @[src/main/core/exu/EXU.scala:49:7, :78:31, :79:24, :80:23, :99:41, :100:{41,59}, :101:41, :102:{41,59}, :103:41, :104:{41,59}, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_jmp_flg = io_pipe_in_bits_id2exe_wb_sel == 3'h2;	// @[src/main/core/exu/EXU.scala:49:7, :108:50]
  assign io_br_target = io_pipe_in_bits_id2exe_reg_pc + io_pipe_in_bits_id2exe_imm_sext;	// @[src/main/core/exu/EXU.scala:49:7, :107:51]
  assign io_alu_out = alu_out;	// @[src/main/core/exu/EXU.scala:49:7, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_pipe_in_ready = in_ready;	// @[src/main/core/exu/EXU.scala:49:7, :151:27]
  assign io_pipe_out_valid = io_pipe_out_valid_0;	// @[src/main/core/exu/EXU.scala:49:7, :154:36]
  assign io_pipe_out_bits_exe2ls_reg_pc = io_pipe_in_bits_id2exe_reg_pc;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_op1_data = op1_data;	// @[src/main/core/exu/EXU.scala:49:7, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_pipe_out_bits_exe2ls_rs2_data = io_pipe_in_bits_id2exe_rs2_data;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_wb_addr = io_pipe_in_bits_id2exe_wb_addr;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_alu_out = alu_out;	// @[src/main/core/exu/EXU.scala:49:7, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_pipe_out_bits_exe2ls_rf_wen = io_pipe_in_bits_id2exe_rf_wen;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_wb_sel = io_pipe_in_bits_id2exe_wb_sel;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_csr_addr = io_pipe_in_bits_id2exe_csr_addr;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_csr_cmd = io_pipe_in_bits_id2exe_csr_cmd;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_mem_wen = io_pipe_in_bits_id2exe_mem_wen;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_mem_op = io_pipe_in_bits_id2exe_mem_op;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_is_irq = io_pipe_in_bits_id2exe_is_irq;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_irq_num = io_pipe_in_bits_id2exe_irq_num;	// @[src/main/core/exu/EXU.scala:49:7]
  assign io_pipe_out_bits_exe2ls_csr_rdata = io_pipe_in_bits_id2exe_csr_rdata;	// @[src/main/core/exu/EXU.scala:49:7]
endmodule

