// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module GPR(	// @[src/main/core/GPR.scala:19:7]
  input         clock,	// @[src/main/core/GPR.scala:19:7]
                reset,	// @[src/main/core/GPR.scala:19:7]
  input  [3:0]  io_gpr_rs1_addr,	// @[src/main/core/GPR.scala:20:16]
                io_gpr_rs2_addr,	// @[src/main/core/GPR.scala:20:16]
  output [31:0] io_gpr_rs1_data,	// @[src/main/core/GPR.scala:20:16]
                io_gpr_rs2_data,	// @[src/main/core/GPR.scala:20:16]
  input  [1:0]  io_gpr_wen,	// @[src/main/core/GPR.scala:20:16]
  input  [3:0]  io_gpr_addr,	// @[src/main/core/GPR.scala:20:16]
  input  [31:0] io_gpr_wdata	// @[src/main/core/GPR.scala:20:16]
);

  reg  [31:0] gpr_0;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_1;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_2;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_3;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_4;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_5;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_6;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_7;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_8;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_9;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_10;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_11;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_12;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_13;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_14;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] gpr_15;	// @[src/main/core/GPR.scala:23:22]
  reg  [31:0] casez_tmp;	// @[src/main/core/GPR.scala:26:27]
  always_comb begin	// @[src/main/core/GPR.scala:26:27]
    casez (io_gpr_rs1_addr)	// @[src/main/core/GPR.scala:26:27]
      4'b0000:
        casez_tmp = gpr_0;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0001:
        casez_tmp = gpr_1;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0010:
        casez_tmp = gpr_2;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0011:
        casez_tmp = gpr_3;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0100:
        casez_tmp = gpr_4;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0101:
        casez_tmp = gpr_5;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0110:
        casez_tmp = gpr_6;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0111:
        casez_tmp = gpr_7;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1000:
        casez_tmp = gpr_8;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1001:
        casez_tmp = gpr_9;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1010:
        casez_tmp = gpr_10;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1011:
        casez_tmp = gpr_11;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1100:
        casez_tmp = gpr_12;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1101:
        casez_tmp = gpr_13;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1110:
        casez_tmp = gpr_14;	// @[src/main/core/GPR.scala:23:22, :26:27]
      default:
        casez_tmp = gpr_15;	// @[src/main/core/GPR.scala:23:22, :26:27]
    endcase	// @[src/main/core/GPR.scala:26:27]
  end // always_comb
  reg  [31:0] casez_tmp_0;	// @[src/main/core/GPR.scala:27:27]
  always_comb begin	// @[src/main/core/GPR.scala:26:27]
    casez (io_gpr_rs2_addr)	// @[src/main/core/GPR.scala:26:27]
      4'b0000:
        casez_tmp_0 = gpr_0;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0001:
        casez_tmp_0 = gpr_1;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0010:
        casez_tmp_0 = gpr_2;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0011:
        casez_tmp_0 = gpr_3;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0100:
        casez_tmp_0 = gpr_4;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0101:
        casez_tmp_0 = gpr_5;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0110:
        casez_tmp_0 = gpr_6;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b0111:
        casez_tmp_0 = gpr_7;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1000:
        casez_tmp_0 = gpr_8;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1001:
        casez_tmp_0 = gpr_9;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1010:
        casez_tmp_0 = gpr_10;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1011:
        casez_tmp_0 = gpr_11;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1100:
        casez_tmp_0 = gpr_12;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1101:
        casez_tmp_0 = gpr_13;	// @[src/main/core/GPR.scala:23:22, :26:27]
      4'b1110:
        casez_tmp_0 = gpr_14;	// @[src/main/core/GPR.scala:23:22, :26:27]
      default:
        casez_tmp_0 = gpr_15;	// @[src/main/core/GPR.scala:23:22, :26:27]
    endcase	// @[src/main/core/GPR.scala:26:27]
  end // always_comb
  wire        _GEN = io_gpr_wen == 2'h1 & (|io_gpr_addr);	// @[src/main/core/GPR.scala:29:{21,31,46}]
  always @(posedge clock) begin	// @[src/main/core/GPR.scala:19:7]
    if (reset) begin	// @[src/main/core/GPR.scala:19:7]
      gpr_0 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_1 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_2 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_3 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_4 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_5 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_6 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_7 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_8 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_9 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_10 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_11 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_12 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_13 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_14 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
      gpr_15 <= 32'h0;	// @[src/main/core/GPR.scala:23:{22,30}]
    end
    else begin	// @[src/main/core/GPR.scala:19:7]
      if (_GEN & ~(|io_gpr_addr))	// @[src/main/core/GPR.scala:23:22, :29:{31,46,66}, :30:26]
        gpr_0 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'h1)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_1 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'h2)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_2 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'h3)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_3 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'h4)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_4 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'h5)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_5 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'h6)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_6 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'h7)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_7 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'h8)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_8 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'h9)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_9 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'hA)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_10 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'hB)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_11 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'hC)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_12 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'hD)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_13 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & io_gpr_addr == 4'hE)	// @[src/main/core/GPR.scala:19:7, :23:22, :29:{31,66}, :30:26]
        gpr_14 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
      if (_GEN & (&io_gpr_addr))	// @[src/main/core/GPR.scala:23:22, :29:{31,66}, :30:26]
        gpr_15 <= io_gpr_wdata;	// @[src/main/core/GPR.scala:23:22]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/GPR.scala:19:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/GPR.scala:19:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/GPR.scala:19:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:15];	// @[src/main/core/GPR.scala:19:7]
    initial begin	// @[src/main/core/GPR.scala:19:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/GPR.scala:19:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/GPR.scala:19:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/GPR.scala:19:7]
        for (logic [4:0] i = 5'h0; i < 5'h10; i += 5'h1) begin
          _RANDOM[i[3:0]] = `RANDOM;	// @[src/main/core/GPR.scala:19:7]
        end	// @[src/main/core/GPR.scala:19:7]
        gpr_0 = _RANDOM[4'h0];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_1 = _RANDOM[4'h1];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_2 = _RANDOM[4'h2];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_3 = _RANDOM[4'h3];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_4 = _RANDOM[4'h4];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_5 = _RANDOM[4'h5];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_6 = _RANDOM[4'h6];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_7 = _RANDOM[4'h7];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_8 = _RANDOM[4'h8];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_9 = _RANDOM[4'h9];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_10 = _RANDOM[4'hA];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_11 = _RANDOM[4'hB];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_12 = _RANDOM[4'hC];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_13 = _RANDOM[4'hD];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_14 = _RANDOM[4'hE];	// @[src/main/core/GPR.scala:19:7, :23:22]
        gpr_15 = _RANDOM[4'hF];	// @[src/main/core/GPR.scala:19:7, :23:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/GPR.scala:19:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/GPR.scala:19:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_gpr_rs1_data = (|io_gpr_rs1_addr) ? casez_tmp : 32'h0;	// @[src/main/core/GPR.scala:19:7, :23:30, :26:{27,45}]
  assign io_gpr_rs2_data = (|io_gpr_rs2_addr) ? casez_tmp_0 : 32'h0;	// @[src/main/core/GPR.scala:19:7, :23:30, :27:{27,45}]
endmodule

