// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module GPR(	// @[src/main/core/GPR.scala:19:7]
  input         clock,	// @[src/main/core/GPR.scala:19:7]
  input  [4:0]  io_gpr_rs1_addr,	// @[src/main/core/GPR.scala:20:16]
                io_gpr_rs2_addr,	// @[src/main/core/GPR.scala:20:16]
  output [31:0] io_gpr_rs1_data,	// @[src/main/core/GPR.scala:20:16]
                io_gpr_rs2_data,	// @[src/main/core/GPR.scala:20:16]
  input  [1:0]  io_gpr_wen,	// @[src/main/core/GPR.scala:20:16]
  input  [4:0]  io_gpr_addr,	// @[src/main/core/GPR.scala:20:16]
  input  [31:0] io_gpr_wdata	// @[src/main/core/GPR.scala:20:16]
);

  wire [31:0] _gpr_ext_R0_data;	// @[src/main/core/GPR.scala:22:18]
  wire [31:0] _gpr_ext_R1_data;	// @[src/main/core/GPR.scala:22:18]
  gpr_32x32 gpr_ext (	// @[src/main/core/GPR.scala:22:18]
    .R0_addr (io_gpr_rs2_addr),
    .R0_en   (1'h1),	// @[src/main/core/GPR.scala:19:7]
    .R0_clk  (clock),
    .R0_data (_gpr_ext_R0_data),
    .R1_addr (io_gpr_rs1_addr),
    .R1_en   (1'h1),	// @[src/main/core/GPR.scala:19:7]
    .R1_clk  (clock),
    .R1_data (_gpr_ext_R1_data),
    .W0_addr (io_gpr_addr),
    .W0_en   (io_gpr_wen == 2'h1 & (|io_gpr_addr)),	// @[src/main/core/GPR.scala:27:{21,31,46}]
    .W0_clk  (clock),
    .W0_data (io_gpr_wdata)
  );
  assign io_gpr_rs1_data = (|io_gpr_rs1_addr) ? _gpr_ext_R1_data : 32'h0;	// @[src/main/core/GPR.scala:19:7, :22:18, :24:{27,45}]
  assign io_gpr_rs2_data = (|io_gpr_rs2_addr) ? _gpr_ext_R0_data : 32'h0;	// @[src/main/core/GPR.scala:19:7, :22:18, :24:27, :25:{27,45}]
endmodule

