// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module IDU(	// @[src/main/core/idu/IDU.scala:54:7]
  input         clock,	// @[src/main/core/idu/IDU.scala:54:7]
                reset,	// @[src/main/core/idu/IDU.scala:54:7]
  output        io_pipe_in_ready,	// @[src/main/core/idu/IDU.scala:55:21]
  input         io_pipe_in_valid,	// @[src/main/core/idu/IDU.scala:55:21]
  input  [31:0] io_pipe_in_bits_if2id_reg_pc,	// @[src/main/core/idu/IDU.scala:55:21]
                io_pipe_in_bits_if2id_inst,	// @[src/main/core/idu/IDU.scala:55:21]
  input         io_pipe_out_ready,	// @[src/main/core/idu/IDU.scala:55:21]
  output        io_pipe_out_valid,	// @[src/main/core/idu/IDU.scala:55:21]
  output [1:0]  io_pipe_out_bits_id2is_processunit,	// @[src/main/core/idu/IDU.scala:55:21]
  output [3:0]  io_pipe_out_bits_id2is_processtpe,	// @[src/main/core/idu/IDU.scala:55:21]
                io_pipe_out_bits_id2is_bjtpe,	// @[src/main/core/idu/IDU.scala:55:21]
  output        io_pipe_out_bits_id2is_rfwe,	// @[src/main/core/idu/IDU.scala:55:21]
  output [3:0]  io_pipe_out_bits_id2is_rd_addr,	// @[src/main/core/idu/IDU.scala:55:21]
  output        io_pipe_out_bits_id2is_ch1tpe,	// @[src/main/core/idu/IDU.scala:55:21]
  output [1:0]  io_pipe_out_bits_id2is_ch2tpe,	// @[src/main/core/idu/IDU.scala:55:21]
  output [3:0]  io_pipe_out_bits_id2is_rs1_addr,	// @[src/main/core/idu/IDU.scala:55:21]
                io_pipe_out_bits_id2is_rs2_addr,	// @[src/main/core/idu/IDU.scala:55:21]
  output [31:0] io_pipe_out_bits_id2is_reg_pc,	// @[src/main/core/idu/IDU.scala:55:21]
                io_pipe_out_bits_id2is_imm,	// @[src/main/core/idu/IDU.scala:55:21]
  output [11:0] io_pipe_out_bits_id2is_csr_addr,	// @[src/main/core/idu/IDU.scala:55:21]
  input         io_flush_flush_flg	// @[src/main/core/idu/IDU.scala:56:22]
);

  wire [28:0] decodeBundle_invInputs = ~(io_pipe_in_bits_if2id_inst[30:2]);	// @[src/main/core/idu/IDU.scala:55:21, src/main/scala/chisel3/util/pla.scala:78:21]
  wire [1:0]  _decodeBundle_andMatrixOutputs_T =
    {decodeBundle_invInputs[0], decodeBundle_invInputs[3]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :91:29, :98:53]
  wire [2:0]  _decodeBundle_andMatrixOutputs_T_1 =
    {decodeBundle_invInputs[0], decodeBundle_invInputs[2], decodeBundle_invInputs[4]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :91:29, :98:53]
  wire [2:0]  _decodeBundle_andMatrixOutputs_T_2 =
    {io_pipe_in_bits_if2id_inst[2], decodeBundle_invInputs[1], decodeBundle_invInputs[2]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [1:0]  _decodeBundle_andMatrixOutputs_T_4 =
    {io_pipe_in_bits_if2id_inst[3], decodeBundle_invInputs[4]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [1:0]  _decodeBundle_andMatrixOutputs_T_6 =
    {io_pipe_in_bits_if2id_inst[2], io_pipe_in_bits_if2id_inst[4]};	// @[src/main/scala/chisel3/util/pla.scala:90:45, :98:53]
  wire [3:0]  _decodeBundle_andMatrixOutputs_T_7 =
    {decodeBundle_invInputs[0],
     decodeBundle_invInputs[2],
     io_pipe_in_bits_if2id_inst[5],
     decodeBundle_invInputs[12]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [1:0]  _decodeBundle_andMatrixOutputs_T_8 =
    {io_pipe_in_bits_if2id_inst[3], io_pipe_in_bits_if2id_inst[5]};	// @[src/main/scala/chisel3/util/pla.scala:90:45, :98:53]
  wire [4:0]  _decodeBundle_andMatrixOutputs_T_9 =
    {decodeBundle_invInputs[0],
     decodeBundle_invInputs[2],
     io_pipe_in_bits_if2id_inst[6],
     decodeBundle_invInputs[10],
     decodeBundle_invInputs[12]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [4:0]  _decodeBundle_andMatrixOutputs_T_10 =
    {io_pipe_in_bits_if2id_inst[4],
     io_pipe_in_bits_if2id_inst[6],
     decodeBundle_invInputs[10],
     decodeBundle_invInputs[11],
     decodeBundle_invInputs[18]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [4:0]  _decodeBundle_andMatrixOutputs_T_14 =
    {decodeBundle_invInputs[0],
     io_pipe_in_bits_if2id_inst[4],
     decodeBundle_invInputs[4],
     io_pipe_in_bits_if2id_inst[12],
     decodeBundle_invInputs[12]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [4:0]  _decodeBundle_andMatrixOutputs_T_15 =
    {decodeBundle_invInputs[0],
     decodeBundle_invInputs[2],
     io_pipe_in_bits_if2id_inst[6],
     io_pipe_in_bits_if2id_inst[12],
     decodeBundle_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [2:0]  _decodeBundle_andMatrixOutputs_T_16 =
    {io_pipe_in_bits_if2id_inst[4],
     io_pipe_in_bits_if2id_inst[6],
     io_pipe_in_bits_if2id_inst[12]};	// @[src/main/scala/chisel3/util/pla.scala:90:45, :98:53]
  wire [4:0]  _decodeBundle_andMatrixOutputs_T_19 =
    {decodeBundle_invInputs[0],
     decodeBundle_invInputs[2],
     io_pipe_in_bits_if2id_inst[6],
     decodeBundle_invInputs[10],
     io_pipe_in_bits_if2id_inst[13]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [2:0]  _decodeBundle_andMatrixOutputs_T_20 =
    {io_pipe_in_bits_if2id_inst[4],
     io_pipe_in_bits_if2id_inst[6],
     io_pipe_in_bits_if2id_inst[13]};	// @[src/main/scala/chisel3/util/pla.scala:90:45, :98:53]
  wire [3:0]  _decodeBundle_andMatrixOutputs_T_21 =
    {decodeBundle_invInputs[0],
     decodeBundle_invInputs[2],
     io_pipe_in_bits_if2id_inst[12],
     io_pipe_in_bits_if2id_inst[13]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [3:0]  _decodeBundle_andMatrixOutputs_T_25 =
    {decodeBundle_invInputs[0],
     io_pipe_in_bits_if2id_inst[6],
     decodeBundle_invInputs[11],
     io_pipe_in_bits_if2id_inst[14]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [4:0]  _decodeBundle_andMatrixOutputs_T_27 =
    {io_pipe_in_bits_if2id_inst[4],
     io_pipe_in_bits_if2id_inst[6],
     decodeBundle_invInputs[10],
     decodeBundle_invInputs[11],
     io_pipe_in_bits_if2id_inst[20]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [2:0]  decodeBundle_immtpe =
    {|{&_decodeBundle_andMatrixOutputs_T_6, &_decodeBundle_andMatrixOutputs_T_8},
     |{&_decodeBundle_andMatrixOutputs_T,
       &_decodeBundle_andMatrixOutputs_T_1,
       &_decodeBundle_andMatrixOutputs_T_2,
       &_decodeBundle_andMatrixOutputs_T_4},
     |{&_decodeBundle_andMatrixOutputs_T_6,
       &_decodeBundle_andMatrixOutputs_T_7,
       &_decodeBundle_andMatrixOutputs_T_19,
       &_decodeBundle_andMatrixOutputs_T_21,
       &_decodeBundle_andMatrixOutputs_T_25}};	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  wire [11:0] imm_i = io_pipe_in_bits_if2id_inst[31:20];	// @[src/main/core/idu/IDU.scala:73:{21,30}]
  wire [11:0] imm_s =
    {io_pipe_in_bits_if2id_inst[31:25], io_pipe_in_bits_if2id_inst[11:7]};	// @[src/main/core/idu/IDU.scala:74:{20,25,39,48}]
  wire [12:0] imm_b =
    {io_pipe_in_bits_if2id_inst[31],
     io_pipe_in_bits_if2id_inst[7],
     io_pipe_in_bits_if2id_inst[30:25],
     io_pipe_in_bits_if2id_inst[11:8],
     1'h0};	// @[src/main/core/idu/IDU.scala:54:7, :75:{20,25,35,44,58,77}]
  wire [20:0] imm_j =
    {io_pipe_in_bits_if2id_inst[31],
     io_pipe_in_bits_if2id_inst[19:12],
     io_pipe_in_bits_if2id_inst[20],
     io_pipe_in_bits_if2id_inst[30:21],
     1'h0};	// @[src/main/core/idu/IDU.scala:54:7, :75:25, :76:{20,35,49,59,79}]
  wire [31:0] imm_u = {io_pipe_in_bits_if2id_inst[31:12], 12'h0};	// @[src/main/core/idu/IDU.scala:77:{20,25,46}, :78:37]
  wire [11:0] _imm_T_1 = decodeBundle_immtpe == 3'h2 ? imm_i : 12'h0;	// @[src/main/core/idu/IDU.scala:73:30, :78:37, src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106]
  reg         in_ready;	// @[src/main/core/idu/IDU.scala:144:27]
  reg         out_valid;	// @[src/main/core/idu/IDU.scala:145:28]
  wire        io_pipe_out_valid_0 = out_valid & ~io_flush_flush_flg;	// @[src/main/core/idu/IDU.scala:145:28, :147:{36,39}]
  reg         c_state;	// @[src/main/core/idu/IDU.scala:150:26]
  wire        n_state =
    ~io_flush_flush_flg
    & (c_state
         ? ~(io_pipe_out_ready & io_pipe_out_valid_0)
         : in_ready & io_pipe_in_valid);	// @[src/main/core/idu/IDU.scala:75:20, :144:27, :147:36, :150:26, :151:30, :156:29, :157:17, :159:{17,55}, :160:37, :161:37, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[src/main/core/idu/IDU.scala:54:7]
    if (reset) begin	// @[src/main/core/idu/IDU.scala:54:7]
      in_ready <= 1'h0;	// @[src/main/core/idu/IDU.scala:54:7, :144:27]
      out_valid <= 1'h0;	// @[src/main/core/idu/IDU.scala:54:7, :145:28]
      c_state <= 1'h0;	// @[src/main/core/idu/IDU.scala:54:7, :150:26]
    end
    else begin	// @[src/main/core/idu/IDU.scala:54:7]
      in_ready <= ~n_state | ~n_state & in_ready;	// @[src/main/core/idu/IDU.scala:144:27, :151:30, :165:20, :167:22, :171:22]
      out_valid <= n_state & (n_state ? ~io_flush_flush_flg : out_valid);	// @[src/main/core/idu/IDU.scala:145:28, :147:39, :151:30, :165:20, :168:23, :172:23]
      c_state <= n_state;	// @[src/main/core/idu/IDU.scala:150:26, :151:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/idu/IDU.scala:54:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/idu/IDU.scala:54:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/idu/IDU.scala:54:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/core/idu/IDU.scala:54:7]
    initial begin	// @[src/main/core/idu/IDU.scala:54:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/idu/IDU.scala:54:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/idu/IDU.scala:54:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/idu/IDU.scala:54:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/core/idu/IDU.scala:54:7]
        in_ready = _RANDOM[/*Zero width*/ 1'b0][0];	// @[src/main/core/idu/IDU.scala:54:7, :144:27]
        out_valid = _RANDOM[/*Zero width*/ 1'b0][1];	// @[src/main/core/idu/IDU.scala:54:7, :144:27, :145:28]
        c_state = _RANDOM[/*Zero width*/ 1'b0][2];	// @[src/main/core/idu/IDU.scala:54:7, :144:27, :150:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/idu/IDU.scala:54:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/idu/IDU.scala:54:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Ebreak ebreak (	// @[src/main/core/idu/IDU.scala:116:29]
    .inst (io_pipe_in_bits_if2id_inst)
  );
  assign io_pipe_in_ready = in_ready;	// @[src/main/core/idu/IDU.scala:54:7, :144:27]
  assign io_pipe_out_valid = io_pipe_out_valid_0;	// @[src/main/core/idu/IDU.scala:54:7, :147:36]
  assign io_pipe_out_bits_id2is_processunit =
    {&_decodeBundle_andMatrixOutputs_T_1,
     |{&_decodeBundle_andMatrixOutputs_T_10,
       &_decodeBundle_andMatrixOutputs_T_16,
       &_decodeBundle_andMatrixOutputs_T_20}};	// @[src/main/core/idu/IDU.scala:54:7, src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  assign io_pipe_out_bits_id2is_processtpe =
    {|{&_decodeBundle_andMatrixOutputs_T_2,
       &_decodeBundle_andMatrixOutputs_T_4,
       &{io_pipe_in_bits_if2id_inst[4],
         decodeBundle_invInputs[4],
         decodeBundle_invInputs[10],
         decodeBundle_invInputs[11],
         decodeBundle_invInputs[12]},
       &_decodeBundle_andMatrixOutputs_T_6,
       &_decodeBundle_andMatrixOutputs_T_7,
       &_decodeBundle_andMatrixOutputs_T_8,
       &_decodeBundle_andMatrixOutputs_T_27},
     |{&{decodeBundle_invInputs[0],
         io_pipe_in_bits_if2id_inst[4],
         decodeBundle_invInputs[4],
         io_pipe_in_bits_if2id_inst[12],
         decodeBundle_invInputs[11]},
       &{decodeBundle_invInputs[2],
         decodeBundle_invInputs[3],
         io_pipe_in_bits_if2id_inst[14]},
       &{decodeBundle_invInputs[0],
         io_pipe_in_bits_if2id_inst[4],
         decodeBundle_invInputs[10],
         io_pipe_in_bits_if2id_inst[13],
         io_pipe_in_bits_if2id_inst[14]}},
     |{&_decodeBundle_andMatrixOutputs_T_10,
       &_decodeBundle_andMatrixOutputs_T_14,
       &{decodeBundle_invInputs[2],
         decodeBundle_invInputs[4],
         io_pipe_in_bits_if2id_inst[13]},
       &_decodeBundle_andMatrixOutputs_T_19,
       &_decodeBundle_andMatrixOutputs_T_21,
       &{decodeBundle_invInputs[0],
         io_pipe_in_bits_if2id_inst[4],
         decodeBundle_invInputs[10],
         decodeBundle_invInputs[11],
         io_pipe_in_bits_if2id_inst[14]},
       &{decodeBundle_invInputs[0],
         io_pipe_in_bits_if2id_inst[4],
         decodeBundle_invInputs[11],
         io_pipe_in_bits_if2id_inst[14],
         decodeBundle_invInputs[28]}},
     |{&_decodeBundle_andMatrixOutputs_T_9,
       &{io_pipe_in_bits_if2id_inst[4],
         io_pipe_in_bits_if2id_inst[6],
         decodeBundle_invInputs[10],
         decodeBundle_invInputs[18],
         decodeBundle_invInputs[19]},
       &{decodeBundle_invInputs[0],
         decodeBundle_invInputs[2],
         io_pipe_in_bits_if2id_inst[12]},
       &_decodeBundle_andMatrixOutputs_T_14,
       &_decodeBundle_andMatrixOutputs_T_15,
       &{decodeBundle_invInputs[0],
         io_pipe_in_bits_if2id_inst[4],
         io_pipe_in_bits_if2id_inst[13],
         decodeBundle_invInputs[12]},
       &_decodeBundle_andMatrixOutputs_T_19,
       &_decodeBundle_andMatrixOutputs_T_21,
       &_decodeBundle_andMatrixOutputs_T_25,
       &{decodeBundle_invInputs[0],
         io_pipe_in_bits_if2id_inst[4],
         io_pipe_in_bits_if2id_inst[5],
         decodeBundle_invInputs[4],
         io_pipe_in_bits_if2id_inst[30]},
       &{decodeBundle_invInputs[0],
         decodeBundle_invInputs[3],
         io_pipe_in_bits_if2id_inst[12],
         decodeBundle_invInputs[11],
         io_pipe_in_bits_if2id_inst[30]}}};	// @[src/main/core/idu/IDU.scala:54:7, src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}]
  assign io_pipe_out_bits_id2is_bjtpe =
    {|{&_decodeBundle_andMatrixOutputs_T_2, &_decodeBundle_andMatrixOutputs_T_8},
     |{&_decodeBundle_andMatrixOutputs_T_21, &_decodeBundle_andMatrixOutputs_T_25},
     |{&_decodeBundle_andMatrixOutputs_T_15, &_decodeBundle_andMatrixOutputs_T_19},
     |{&_decodeBundle_andMatrixOutputs_T_2,
       &_decodeBundle_andMatrixOutputs_T_9,
       &_decodeBundle_andMatrixOutputs_T_19,
       &_decodeBundle_andMatrixOutputs_T_21}};	// @[src/main/core/idu/IDU.scala:54:7, src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  assign io_pipe_out_bits_id2is_rfwe =
    |{&_decodeBundle_andMatrixOutputs_T_7,
      &_decodeBundle_andMatrixOutputs_T_10,
      &_decodeBundle_andMatrixOutputs_T_19,
      &_decodeBundle_andMatrixOutputs_T_21,
      &_decodeBundle_andMatrixOutputs_T_25,
      &_decodeBundle_andMatrixOutputs_T_27};	// @[src/main/core/idu/IDU.scala:54:7, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  assign io_pipe_out_bits_id2is_rd_addr = io_pipe_in_bits_if2id_inst[10:7];	// @[src/main/core/idu/IDU.scala:54:7, :74:39, :99:36]
  assign io_pipe_out_bits_id2is_ch1tpe =
    |{&_decodeBundle_andMatrixOutputs_T_2,
      &{io_pipe_in_bits_if2id_inst[2],
        decodeBundle_invInputs[1],
        decodeBundle_invInputs[3]},
      &_decodeBundle_andMatrixOutputs_T_8,
      &_decodeBundle_andMatrixOutputs_T_10,
      &_decodeBundle_andMatrixOutputs_T_27};	// @[src/main/core/idu/IDU.scala:54:7, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}]
  assign io_pipe_out_bits_id2is_ch2tpe =
    {|{&_decodeBundle_andMatrixOutputs_T_2,
       &_decodeBundle_andMatrixOutputs_T_8,
       &_decodeBundle_andMatrixOutputs_T_16,
       &_decodeBundle_andMatrixOutputs_T_20},
     |{&_decodeBundle_andMatrixOutputs_T,
       &_decodeBundle_andMatrixOutputs_T_4,
       &_decodeBundle_andMatrixOutputs_T_6,
       &_decodeBundle_andMatrixOutputs_T_10,
       &_decodeBundle_andMatrixOutputs_T_16,
       &_decodeBundle_andMatrixOutputs_T_20,
       &_decodeBundle_andMatrixOutputs_T_27}};	// @[src/main/core/idu/IDU.scala:54:7, src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  assign io_pipe_out_bits_id2is_rs1_addr =
    io_pipe_in_bits_if2id_inst[6:0] == 7'h37 ? 4'h0 : io_pipe_in_bits_if2id_inst[18:15];	// @[src/main/core/idu/IDU.scala:54:7, :92:22, :102:{43,51,78}, src/main/scala/chisel3/util/pla.scala:114:36]
  assign io_pipe_out_bits_id2is_rs2_addr = io_pipe_in_bits_if2id_inst[23:20];	// @[src/main/core/idu/IDU.scala:54:7, :103:{37,44}]
  assign io_pipe_out_bits_id2is_reg_pc = io_pipe_in_bits_if2id_reg_pc;	// @[src/main/core/idu/IDU.scala:54:7]
  assign io_pipe_out_bits_id2is_imm =
    decodeBundle_immtpe == 3'h1
      ? {{19{imm_b[12]}}, imm_b}
      : decodeBundle_immtpe == 3'h3
          ? {{20{imm_s[11]}}, imm_s}
          : decodeBundle_immtpe == 3'h4
              ? {{11{imm_j[20]}}, imm_j}
              : decodeBundle_immtpe == 3'h5 ? imm_u : {{20{_imm_T_1[11]}}, _imm_T_1};	// @[src/main/core/idu/IDU.scala:54:7, :74:48, :75:77, :76:79, :77:46, :78:37, src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106]
  assign io_pipe_out_bits_id2is_csr_addr = imm_i;	// @[src/main/core/idu/IDU.scala:54:7, :73:30]
endmodule

