// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module IFU(	// @[src/main/core/ifu/IFU.scala:49:7]
  input         clock,	// @[src/main/core/ifu/IFU.scala:49:7]
                reset,	// @[src/main/core/ifu/IFU.scala:49:7]
  output [31:0] io_imem_araddr,	// @[src/main/core/ifu/IFU.scala:50:16]
  output        io_imem_arvalid,	// @[src/main/core/ifu/IFU.scala:50:16]
  input         io_imem_arready,	// @[src/main/core/ifu/IFU.scala:50:16]
  input  [31:0] io_imem_rdata,	// @[src/main/core/ifu/IFU.scala:50:16]
  input         io_imem_rvalid,	// @[src/main/core/ifu/IFU.scala:50:16]
  output        io_imem_rready,	// @[src/main/core/ifu/IFU.scala:50:16]
                io_pipe_in_ready,	// @[src/main/core/ifu/IFU.scala:51:21]
  input         io_pipe_in_valid,	// @[src/main/core/ifu/IFU.scala:51:21]
                io_pipe_out_ready,	// @[src/main/core/ifu/IFU.scala:51:21]
  output        io_pipe_out_valid,	// @[src/main/core/ifu/IFU.scala:51:21]
  output [31:0] io_pipe_out_bits_if2id_reg_pc,	// @[src/main/core/ifu/IFU.scala:51:21]
                io_pipe_out_bits_if2id_inst,	// @[src/main/core/ifu/IFU.scala:51:21]
  input         io_bj_valid,	// @[src/main/core/ifu/IFU.scala:52:19]
  input  [31:0] io_bj_target,	// @[src/main/core/ifu/IFU.scala:52:19]
  output        io_flush_flush_flg	// @[src/main/core/ifu/IFU.scala:53:22]
);

  wire        io_pipe_out_valid_0;	// @[src/main/core/ifu/IFU.scala:108:36]
  wire        _n_state_T_5 = io_pipe_out_ready & io_pipe_out_valid_0;	// @[src/main/core/ifu/IFU.scala:108:36, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [31:0] reg_pc;	// @[src/main/core/ifu/IFU.scala:62:18]
  wire [31:0] pc_next = io_bj_valid ? io_bj_target : reg_pc + 32'h4;	// @[src/main/core/ifu/IFU.scala:58:23, :62:18, :65:27, :67:19]
  wire        flush_flg = io_bj_valid & io_bj_target != reg_pc;	// @[src/main/core/ifu/IFU.scala:62:18, :74:{33,50}]
  reg         in_ready;	// @[src/main/core/ifu/IFU.scala:105:27]
  reg         out_valid;	// @[src/main/core/ifu/IFU.scala:106:28]
  assign io_pipe_out_valid_0 = out_valid & ~flush_flg;	// @[src/main/core/ifu/IFU.scala:74:33, :106:28, :108:{36,39}]
  reg         arvalid;	// @[src/main/core/ifu/IFU.scala:110:26]
  reg         rready;	// @[src/main/core/ifu/IFU.scala:111:25]
  reg  [2:0]  c_state;	// @[src/main/core/ifu/IFU.scala:117:26]
  wire        AXI_R_fire = io_imem_rvalid & rready;	// @[src/main/core/ifu/IFU.scala:111:25, :122:37]
  wire [2:0]  n_state =
    c_state == 3'h4
      ? {~AXI_R_fire, 2'h0}
      : c_state == 3'h3
          ? (_n_state_T_5 | flush_flg ? 3'h0 : 3'h3)
          : c_state == 3'h2
              ? (AXI_R_fire & ~flush_flg
                   ? 3'h3
                   : ~AXI_R_fire & flush_flg
                       ? 3'h4
                       : {1'h0, ~(AXI_R_fire & flush_flg), 1'h0})
              : c_state == 3'h1
                  ? (arvalid & io_imem_arready ? 3'h2 : 3'h1)
                  : {2'h0,
                     c_state == 3'h0 & io_pipe_in_valid & io_imem_arready & ~flush_flg};	// @[src/main/core/ifu/IFU.scala:49:7, :74:33, :108:39, :110:26, :117:26, :118:30, :121:31, :122:37, :126:36, :127:{26,38}, :128:35, :132:51, :133:38, :134:38, :135:{38,72,101}, :136:{38,56}, :137:38, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock or posedge reset) begin	// @[src/main/core/ifu/IFU.scala:49:7]
    if (reset)	// @[src/main/core/ifu/IFU.scala:49:7]
      reg_pc <= 32'h30000000;	// @[src/main/core/ifu/IFU.scala:62:18]
    else if (_n_state_T_5 | io_bj_valid)	// @[src/main/core/ifu/IFU.scala:62:57, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      reg_pc <= pc_next;	// @[src/main/core/ifu/IFU.scala:58:23, :62:18]
  end // always @(posedge, posedge)
  wire        _GEN = n_state == 3'h0;	// @[src/main/core/ifu/IFU.scala:118:30, :133:38, :140:20]
  wire        _GEN_0 = n_state == 3'h1;	// @[src/main/core/ifu/IFU.scala:117:26, :118:30, :140:20]
  wire        _GEN_1 = n_state == 3'h2;	// @[src/main/core/ifu/IFU.scala:118:30, :134:38, :140:20]
  wire        _GEN_2 = n_state == 3'h3;	// @[src/main/core/ifu/IFU.scala:118:30, :135:38, :140:20]
  wire        _GEN_3 = n_state == 3'h4;	// @[src/main/core/ifu/IFU.scala:118:30, :135:72, :140:20]
  wire        _GEN_4 = _GEN_1 | _GEN_2 | _GEN_3;	// @[src/main/core/ifu/IFU.scala:105:27, :140:20, :159:22, :167:22, :175:22]
  always @(posedge clock) begin	// @[src/main/core/ifu/IFU.scala:49:7]
    if (reset) begin	// @[src/main/core/ifu/IFU.scala:49:7]
      in_ready <= 1'h0;	// @[src/main/core/ifu/IFU.scala:49:7, :105:27]
      out_valid <= 1'h0;	// @[src/main/core/ifu/IFU.scala:49:7, :106:28]
      arvalid <= 1'h0;	// @[src/main/core/ifu/IFU.scala:49:7, :110:26]
      rready <= 1'h0;	// @[src/main/core/ifu/IFU.scala:49:7, :111:25]
      c_state <= 3'h1;	// @[src/main/core/ifu/IFU.scala:117:26]
    end
    else begin	// @[src/main/core/ifu/IFU.scala:49:7]
      in_ready <= _GEN | ~(_GEN_0 | _GEN_4) & in_ready;	// @[src/main/core/ifu/IFU.scala:105:27, :140:20, :143:22, :151:22, :159:22, :167:22, :175:22]
      out_valid <= ~(_GEN | _GEN_0 | _GEN_1) & (_GEN_2 | ~_GEN_3 & out_valid);	// @[src/main/core/ifu/IFU.scala:106:28, :140:20, :144:23, :152:23, :160:23, :168:23, :176:23]
      arvalid <= ~_GEN & (_GEN_0 | ~_GEN_4 & arvalid);	// @[src/main/core/ifu/IFU.scala:105:27, :110:26, :140:20, :146:21, :154:21, :159:22, :162:21, :167:22, :170:21, :175:22, :178:21]
      rready <= ~(_GEN | _GEN_0) & (_GEN_1 | ~_GEN_2 & (_GEN_3 | rready));	// @[src/main/core/ifu/IFU.scala:111:25, :140:20, :147:20, :155:20, :163:20, :171:20, :179:20]
      c_state <= n_state;	// @[src/main/core/ifu/IFU.scala:117:26, :118:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/ifu/IFU.scala:49:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/ifu/IFU.scala:49:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/ifu/IFU.scala:49:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[src/main/core/ifu/IFU.scala:49:7]
    initial begin	// @[src/main/core/ifu/IFU.scala:49:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/ifu/IFU.scala:49:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/ifu/IFU.scala:49:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/ifu/IFU.scala:49:7]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[src/main/core/ifu/IFU.scala:49:7]
        end	// @[src/main/core/ifu/IFU.scala:49:7]
        reg_pc = _RANDOM[1'h0];	// @[src/main/core/ifu/IFU.scala:49:7, :62:18]
        in_ready = _RANDOM[1'h1][0];	// @[src/main/core/ifu/IFU.scala:49:7, :105:27]
        out_valid = _RANDOM[1'h1][1];	// @[src/main/core/ifu/IFU.scala:49:7, :105:27, :106:28]
        arvalid = _RANDOM[1'h1][2];	// @[src/main/core/ifu/IFU.scala:49:7, :105:27, :110:26]
        rready = _RANDOM[1'h1][3];	// @[src/main/core/ifu/IFU.scala:49:7, :105:27, :111:25]
        c_state = _RANDOM[1'h1][6:4];	// @[src/main/core/ifu/IFU.scala:49:7, :105:27, :117:26]
      `endif // RANDOMIZE_REG_INIT
      if (reset)	// @[src/main/core/ifu/IFU.scala:49:7]
        reg_pc = 32'h30000000;	// @[src/main/core/ifu/IFU.scala:62:18]
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/ifu/IFU.scala:49:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/ifu/IFU.scala:49:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_imem_araddr = flush_flg ? io_bj_target : reg_pc;	// @[src/main/core/ifu/IFU.scala:49:7, :62:18, :74:33, :77:26]
  assign io_imem_arvalid = arvalid;	// @[src/main/core/ifu/IFU.scala:49:7, :110:26]
  assign io_imem_rready = rready;	// @[src/main/core/ifu/IFU.scala:49:7, :111:25]
  assign io_pipe_in_ready = in_ready;	// @[src/main/core/ifu/IFU.scala:49:7, :105:27]
  assign io_pipe_out_valid = io_pipe_out_valid_0;	// @[src/main/core/ifu/IFU.scala:49:7, :108:36]
  assign io_pipe_out_bits_if2id_reg_pc = reg_pc;	// @[src/main/core/ifu/IFU.scala:49:7, :62:18]
  assign io_pipe_out_bits_if2id_inst = io_imem_rdata;	// @[src/main/core/ifu/IFU.scala:49:7]
  assign io_flush_flush_flg = io_bj_valid;	// @[src/main/core/ifu/IFU.scala:49:7]
endmodule

