// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module WBU(	// @[src/main/core/wbu/WBU.scala:37:7]
  input         clock,	// @[src/main/core/wbu/WBU.scala:37:7]
                reset,	// @[src/main/core/wbu/WBU.scala:37:7]
  output [1:0]  io_gpr_wen,	// @[src/main/core/wbu/WBU.scala:38:16]
  output [4:0]  io_gpr_addr,	// @[src/main/core/wbu/WBU.scala:38:16]
  output [31:0] io_gpr_wdata,	// @[src/main/core/wbu/WBU.scala:38:16]
  output [11:0] io_csr_addr,	// @[src/main/core/wbu/WBU.scala:38:16]
  output [2:0]  io_csr_cmd,	// @[src/main/core/wbu/WBU.scala:38:16]
  output [31:0] io_csr_wdata,	// @[src/main/core/wbu/WBU.scala:38:16]
  output        io_is_irq,	// @[src/main/core/wbu/WBU.scala:38:16]
  output [3:0]  io_irq_num,	// @[src/main/core/wbu/WBU.scala:38:16]
  output        io_irq_valid,	// @[src/main/core/wbu/WBU.scala:38:16]
                io_pipe_in_ready,	// @[src/main/core/wbu/WBU.scala:39:21]
  input         io_pipe_in_valid,	// @[src/main/core/wbu/WBU.scala:39:21]
  input  [31:0] io_pipe_in_bits_ls2wb_reg_pc,	// @[src/main/core/wbu/WBU.scala:39:21]
  input  [4:0]  io_pipe_in_bits_ls2wb_wb_addr,	// @[src/main/core/wbu/WBU.scala:39:21]
  input  [1:0]  io_pipe_in_bits_ls2wb_rf_wen,	// @[src/main/core/wbu/WBU.scala:39:21]
  input  [31:0] io_pipe_in_bits_ls2wb_wb_data,	// @[src/main/core/wbu/WBU.scala:39:21]
                io_pipe_in_bits_ls2wb_csr_wdata,	// @[src/main/core/wbu/WBU.scala:39:21]
  input  [11:0] io_pipe_in_bits_ls2wb_csr_addr,	// @[src/main/core/wbu/WBU.scala:39:21]
  input  [2:0]  io_pipe_in_bits_ls2wb_csr_cmd,	// @[src/main/core/wbu/WBU.scala:39:21]
  input         io_pipe_in_bits_ls2wb_is_irq,	// @[src/main/core/wbu/WBU.scala:39:21]
  input  [3:0]  io_pipe_in_bits_ls2wb_irq_num,	// @[src/main/core/wbu/WBU.scala:39:21]
  input         io_pipe_out_ready,	// @[src/main/core/wbu/WBU.scala:39:21]
  output        io_pipe_out_valid,	// @[src/main/core/wbu/WBU.scala:39:21]
  input         io_hazard_flush_flg	// @[src/main/core/wbu/WBU.scala:45:23]
);

  reg  in_ready;	// @[src/main/core/wbu/WBU.scala:76:27]
  reg  out_valid;	// @[src/main/core/wbu/WBU.scala:77:28]
  reg  c_state;	// @[src/main/core/wbu/WBU.scala:82:26]
  wire n_state = c_state ? ~(io_pipe_out_ready & out_valid) : in_ready & io_pipe_in_valid;	// @[src/main/core/wbu/WBU.scala:51:22, :76:27, :77:28, :82:26, :83:30, :88:51, :89:33, :90:33, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire _GEN = n_state & io_pipe_in_valid & ~io_hazard_flush_flg;	// @[src/main/core/wbu/WBU.scala:51:{16,43}, :83:30, :93:20, :98:24]
  always @(posedge clock) begin	// @[src/main/core/wbu/WBU.scala:37:7]
    if (reset) begin	// @[src/main/core/wbu/WBU.scala:37:7]
      in_ready <= 1'h0;	// @[src/main/core/wbu/WBU.scala:37:7, :76:27]
      out_valid <= 1'h0;	// @[src/main/core/wbu/WBU.scala:37:7, :77:28]
      c_state <= 1'h0;	// @[src/main/core/wbu/WBU.scala:37:7, :82:26]
    end
    else begin	// @[src/main/core/wbu/WBU.scala:37:7]
      in_ready <= ~n_state | ~n_state & in_ready;	// @[src/main/core/wbu/WBU.scala:76:27, :83:30, :93:20, :95:22, :102:22]
      out_valid <= n_state & (n_state | out_valid);	// @[src/main/core/wbu/WBU.scala:77:28, :83:30, :93:20, :96:23, :103:23]
      c_state <= n_state;	// @[src/main/core/wbu/WBU.scala:82:26, :83:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/wbu/WBU.scala:37:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/wbu/WBU.scala:37:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/wbu/WBU.scala:37:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/core/wbu/WBU.scala:37:7]
    initial begin	// @[src/main/core/wbu/WBU.scala:37:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/wbu/WBU.scala:37:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/wbu/WBU.scala:37:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/wbu/WBU.scala:37:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/core/wbu/WBU.scala:37:7]
        in_ready = _RANDOM[/*Zero width*/ 1'b0][0];	// @[src/main/core/wbu/WBU.scala:37:7, :76:27]
        out_valid = _RANDOM[/*Zero width*/ 1'b0][1];	// @[src/main/core/wbu/WBU.scala:37:7, :76:27, :77:28]
        c_state = _RANDOM[/*Zero width*/ 1'b0][2];	// @[src/main/core/wbu/WBU.scala:37:7, :76:27, :82:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/wbu/WBU.scala:37:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/wbu/WBU.scala:37:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_gpr_wen = _GEN ? io_pipe_in_bits_ls2wb_rf_wen : 2'h0;	// @[src/main/core/wbu/WBU.scala:37:7, :51:{16,22}, :93:20, :98:24]
  assign io_gpr_addr = io_pipe_in_bits_ls2wb_wb_addr;	// @[src/main/core/wbu/WBU.scala:37:7]
  assign io_gpr_wdata = io_pipe_in_bits_ls2wb_wb_data;	// @[src/main/core/wbu/WBU.scala:37:7]
  assign io_csr_addr = io_pipe_in_bits_ls2wb_csr_addr;	// @[src/main/core/wbu/WBU.scala:37:7]
  assign io_csr_cmd = _GEN ? io_pipe_in_bits_ls2wb_csr_cmd : 3'h0;	// @[src/main/core/wbu/WBU.scala:37:7, :51:16, :56:{16,22}, :93:20, :98:24, :99:24]
  assign io_csr_wdata = io_pipe_in_bits_ls2wb_csr_wdata;	// @[src/main/core/wbu/WBU.scala:37:7]
  assign io_is_irq = io_pipe_in_bits_ls2wb_is_irq;	// @[src/main/core/wbu/WBU.scala:37:7]
  assign io_irq_num = io_pipe_in_bits_ls2wb_irq_num;	// @[src/main/core/wbu/WBU.scala:37:7]
  assign io_irq_valid = io_pipe_in_valid & ~io_hazard_flush_flg;	// @[src/main/core/wbu/WBU.scala:37:7, :51:43, :114:38]
  assign io_pipe_in_ready = in_ready;	// @[src/main/core/wbu/WBU.scala:37:7, :76:27]
  assign io_pipe_out_valid = out_valid;	// @[src/main/core/wbu/WBU.scala:37:7, :77:28]
endmodule

