// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module WBU(	// @[src/main/core/wbu/WBU.scala:46:7]
  output        io_gpr_we,	// @[src/main/core/wbu/WBU.scala:47:16]
  output [3:0]  io_gpr_waddr,	// @[src/main/core/wbu/WBU.scala:47:16]
  output [31:0] io_gpr_wdata,	// @[src/main/core/wbu/WBU.scala:47:16]
  output        io_pipe_in_ready,	// @[src/main/core/wbu/WBU.scala:48:21]
  input         io_pipe_in_valid,	// @[src/main/core/wbu/WBU.scala:48:21]
                io_pipe_in_bits_exe2wb_gpr_we,	// @[src/main/core/wbu/WBU.scala:48:21]
  input  [31:0] io_pipe_in_bits_exe2wb_gpr_wdata,	// @[src/main/core/wbu/WBU.scala:48:21]
  input  [3:0]  io_pipe_in_bits_exe2wb_gpr_waddr,	// @[src/main/core/wbu/WBU.scala:48:21]
  input         io_pipe_out_ready,	// @[src/main/core/wbu/WBU.scala:48:21]
  output        io_pipe_out_valid,	// @[src/main/core/wbu/WBU.scala:48:21]
                io_for_gpr_we,	// @[src/main/core/wbu/WBU.scala:49:20]
  output [31:0] io_for_gpr_wdata,	// @[src/main/core/wbu/WBU.scala:49:20]
  output [3:0]  io_for_gpr_waddr	// @[src/main/core/wbu/WBU.scala:49:20]
);

  assign io_gpr_we = io_pipe_in_bits_exe2wb_gpr_we;	// @[src/main/core/wbu/WBU.scala:46:7]
  assign io_gpr_waddr = io_pipe_in_bits_exe2wb_gpr_waddr;	// @[src/main/core/wbu/WBU.scala:46:7]
  assign io_gpr_wdata = io_pipe_in_bits_exe2wb_gpr_wdata;	// @[src/main/core/wbu/WBU.scala:46:7]
  assign io_pipe_in_ready = 1'h1;	// @[src/main/core/wbu/WBU.scala:46:7, :53:22]
  assign io_pipe_out_valid = 1'h1;	// @[src/main/core/wbu/WBU.scala:46:7, :53:22]
  assign io_for_gpr_we = io_pipe_in_bits_exe2wb_gpr_we;	// @[src/main/core/wbu/WBU.scala:46:7]
  assign io_for_gpr_wdata = io_pipe_in_bits_exe2wb_gpr_wdata;	// @[src/main/core/wbu/WBU.scala:46:7]
  assign io_for_gpr_waddr = io_pipe_in_bits_exe2wb_gpr_waddr;	// @[src/main/core/wbu/WBU.scala:46:7]
endmodule

