// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Xbar_new(	// @[src/main/bus/Xbar_new.scala:22:7]
  input         clock,	// @[src/main/bus/Xbar_new.scala:22:7]
                reset,	// @[src/main/bus/Xbar_new.scala:22:7]
  input  [31:0] io_imem_araddr,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_imem_arvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_imem_arready,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [3:0]  io_imem_arid,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [7:0]  io_imem_arlen,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [2:0]  io_imem_arsize,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [1:0]  io_imem_arburst,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [31:0] io_imem_rdata,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_imem_rvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_imem_rready,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [31:0] io_imem_awaddr,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_imem_awvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [3:0]  io_imem_awid,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [7:0]  io_imem_awlen,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [2:0]  io_imem_awsize,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [1:0]  io_imem_awburst,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [31:0] io_imem_wdata,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [3:0]  io_imem_wstrb,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_imem_wvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
                io_imem_wlast,	// @[src/main/bus/Xbar_new.scala:23:16]
                io_imem_bready,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [31:0] io_dmem_araddr,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_dmem_arvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_dmem_arready,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [2:0]  io_dmem_arsize,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [31:0] io_dmem_rdata,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [1:0]  io_dmem_rresp,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_dmem_rvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_dmem_rready,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [31:0] io_dmem_awaddr,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_dmem_awvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_dmem_awready,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [2:0]  io_dmem_awsize,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [31:0] io_dmem_wdata,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [3:0]  io_dmem_wstrb,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_dmem_wvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_dmem_wready,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [1:0]  io_dmem_bresp,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_dmem_bvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_dmem_bready,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [31:0] io_soc_araddr,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_soc_arvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_soc_arready,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [3:0]  io_soc_arid,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [7:0]  io_soc_arlen,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [2:0]  io_soc_arsize,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [1:0]  io_soc_arburst,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [31:0] io_soc_rdata,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [1:0]  io_soc_rresp,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_soc_rvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_soc_rready,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_soc_rlast,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [31:0] io_soc_awaddr,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_soc_awvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_soc_awready,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [3:0]  io_soc_awid,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [7:0]  io_soc_awlen,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [2:0]  io_soc_awsize,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [1:0]  io_soc_awburst,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [31:0] io_soc_wdata,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [3:0]  io_soc_wstrb,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_soc_wvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_soc_wready,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_soc_wlast,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [1:0]  io_soc_bresp,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_soc_bvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_soc_bready,	// @[src/main/bus/Xbar_new.scala:23:16]
  output [31:0] io_clint_araddr,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_clint_arvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_clint_arready,	// @[src/main/bus/Xbar_new.scala:23:16]
  input  [31:0] io_clint_rdata,	// @[src/main/bus/Xbar_new.scala:23:16]
  input         io_clint_rvalid,	// @[src/main/bus/Xbar_new.scala:23:16]
  output        io_clint_rready	// @[src/main/bus/Xbar_new.scala:23:16]
);

  reg  [1:0]  c_state;	// @[src/main/bus/Xbar_new.scala:27:26]
  wire        isdmem = io_dmem_arvalid | io_dmem_awvalid;	// @[src/main/bus/Xbar_new.scala:34:38]
  wire        isimem = io_imem_arvalid & ~(isdmem | (&c_state) | c_state == 2'h2);	// @[src/main/bus/Xbar_new.scala:27:26, :34:{21,38}, :35:{21,42,61,75,86}]
  wire        isclint =
    (|(io_dmem_araddr[31:25])) & io_dmem_araddr < 32'h2010000 | (|(io_dmem_awaddr[31:25]))
    & io_dmem_awaddr < 32'h2010000;	// @[src/main/bus/Xbar_new.scala:32:{41,65,83}, :33:{41,65,83}, :37:33]
  wire        _n_state_T_2 = isdmem & isclint;	// @[src/main/bus/Xbar_new.scala:34:38, :37:33, :49:21]
  wire        _n_state_T_10 = c_state == 2'h1;	// @[src/main/bus/Xbar_new.scala:27:26, :45:42, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _n_state_T_12 = c_state == 2'h2;	// @[src/main/bus/Xbar_new.scala:27:26, :35:86, :45:42]
  reg  [1:0]  casez_tmp;	// @[src/main/bus/Xbar_new.scala:45:42]
  always_comb begin	// @[src/main/bus/Xbar_new.scala:45:42]
    casez (c_state)	// @[src/main/bus/Xbar_new.scala:27:26, :45:42]
      2'b00:
        casez_tmp = isimem ? 2'h1 : isdmem & ~isclint ? 2'h2 : {2{_n_state_T_2}};	// @[src/main/bus/Xbar_new.scala:34:38, :35:{21,86}, :37:33, :45:42, :48:{21,24}, :49:21, src/main/scala/chisel3/util/Mux.scala:126:16]
      2'b01:
        casez_tmp = io_soc_rvalid & io_soc_rlast ? {1'h0, io_imem_arvalid} : 2'h1;	// @[src/main/bus/Xbar_new.scala:22:7, :41:36, :45:42, :51:{27,43}, src/main/scala/chisel3/util/Mux.scala:126:16]
      2'b10:
        casez_tmp = {~(io_soc_rvalid | io_soc_bvalid), 1'h0};	// @[src/main/bus/Xbar_new.scala:22:7, :42:36, :45:42, :52:27]
      default:
        casez_tmp = io_clint_rvalid | io_soc_bvalid ? 2'h0 : 2'h3;	// @[src/main/bus/AXI.scala:152:25, :158:22, :171:23, :184:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :35:61, :43:40, :45:42, :53:27, :61:20, :65:42, :67:41, :101:23, :107:23, :118:24, :125:24]
    endcase	// @[src/main/bus/Xbar_new.scala:27:26, :45:42]
  end // always_comb
  wire [1:0]  n_state = casez_tmp;	// @[src/main/bus/Xbar_new.scala:28:30, :45:42]
  wire        _GEN = c_state == 2'h0;	// @[src/main/bus/AXI.scala:152:25, :158:22, :171:23, :184:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :27:26, :61:20, :65:42, :67:41, :101:23, :107:23, :118:24, :125:24]
  wire        _GEN_0 = isdmem & ~isclint;	// @[src/main/bus/Xbar_new.scala:34:38, :37:33, :48:24, :65:31]
  wire        _GEN_1 = isimem | _GEN_0;	// @[src/main/bus/Xbar_new.scala:35:21, :63:25, :65:{31,42}, :67:41, :134:25]
  wire        _GEN_2 = _GEN ? isimem : _n_state_T_10;	// @[src/main/bus/AXI.scala:157:22, src/main/bus/Xbar_new.scala:35:21, :45:42, :61:20, :63:25, :86:23]
  reg  [31:0] casez_tmp_0;	// @[src/main/bus/Xbar_new.scala:61:20, :63:25]
  always_comb begin	// @[src/main/bus/AXI.scala:147:25, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :113:23]
    casez (c_state)	// @[src/main/bus/AXI.scala:147:25, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :113:23]
      2'b00:
        casez_tmp_0 = isimem ? io_imem_araddr : _GEN_0 ? io_dmem_araddr : 32'h0;	// @[src/main/bus/AXI.scala:147:25, src/main/bus/Xbar_new.scala:35:21, :45:42, :61:20, :63:25, :65:{31,42}, :86:23, :113:23]
      2'b01:
        casez_tmp_0 = io_imem_araddr;	// @[src/main/bus/AXI.scala:147:25, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :113:23]
      2'b10:
        casez_tmp_0 = io_dmem_araddr;	// @[src/main/bus/AXI.scala:147:25, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :113:23]
      default:
        casez_tmp_0 = 32'h0;	// @[src/main/bus/AXI.scala:147:25, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :86:23, :113:23]
    endcase	// @[src/main/bus/AXI.scala:147:25, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :113:23]
  end // always_comb
  reg  [2:0]  casez_tmp_1;	// @[src/main/bus/Xbar_new.scala:61:20, :63:25]
  always_comb begin	// @[src/main/bus/AXI.scala:151:25, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :117:23]
    casez (c_state)	// @[src/main/bus/AXI.scala:151:25, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :117:23]
      2'b00:
        casez_tmp_1 = isimem ? io_imem_arsize : _GEN_0 ? io_dmem_arsize : 3'h0;	// @[src/main/bus/AXI.scala:151:25, src/main/bus/Xbar_new.scala:35:21, :45:42, :61:20, :63:25, :65:{31,42}, :117:23]
      2'b01:
        casez_tmp_1 = io_imem_arsize;	// @[src/main/bus/AXI.scala:151:25, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :117:23]
      2'b10:
        casez_tmp_1 = io_dmem_arsize;	// @[src/main/bus/AXI.scala:151:25, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :117:23]
      default:
        casez_tmp_1 = 3'h0;	// @[src/main/bus/AXI.scala:151:25, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :117:23]
    endcase	// @[src/main/bus/AXI.scala:151:25, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :117:23]
  end // always_comb
  reg  [31:0] casez_tmp_2;	// @[src/main/bus/Xbar_new.scala:61:20, :63:25]
  always_comb begin	// @[src/main/bus/AXI.scala:166:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :120:23]
    casez (c_state)	// @[src/main/bus/AXI.scala:166:23, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :120:23]
      2'b00:
        casez_tmp_2 = isimem ? io_imem_awaddr : _GEN_0 ? io_dmem_awaddr : 32'h0;	// @[src/main/bus/AXI.scala:166:23, src/main/bus/Xbar_new.scala:35:21, :45:42, :61:20, :63:25, :65:{31,42}, :86:23, :120:23]
      2'b01:
        casez_tmp_2 = io_imem_awaddr;	// @[src/main/bus/AXI.scala:166:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :120:23]
      2'b10:
        casez_tmp_2 = io_dmem_awaddr;	// @[src/main/bus/AXI.scala:166:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :120:23]
      default:
        casez_tmp_2 = 32'h0;	// @[src/main/bus/AXI.scala:166:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :86:23, :120:23]
    endcase	// @[src/main/bus/AXI.scala:166:23, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :120:23]
  end // always_comb
  reg  [2:0]  casez_tmp_3;	// @[src/main/bus/Xbar_new.scala:61:20, :63:25]
  always_comb begin	// @[src/main/bus/AXI.scala:170:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :124:23]
    casez (c_state)	// @[src/main/bus/AXI.scala:170:23, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :124:23]
      2'b00:
        casez_tmp_3 = isimem ? io_imem_awsize : _GEN_0 ? io_dmem_awsize : 3'h0;	// @[src/main/bus/AXI.scala:170:23, src/main/bus/Xbar_new.scala:35:21, :45:42, :61:20, :63:25, :65:{31,42}, :117:23, :124:23]
      2'b01:
        casez_tmp_3 = io_imem_awsize;	// @[src/main/bus/AXI.scala:170:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :124:23]
      2'b10:
        casez_tmp_3 = io_dmem_awsize;	// @[src/main/bus/AXI.scala:170:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :124:23]
      default:
        casez_tmp_3 = 3'h0;	// @[src/main/bus/AXI.scala:170:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :117:23, :124:23]
    endcase	// @[src/main/bus/AXI.scala:170:23, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :124:23]
  end // always_comb
  reg  [31:0] casez_tmp_4;	// @[src/main/bus/Xbar_new.scala:61:20, :63:25]
  always_comb begin	// @[src/main/bus/AXI.scala:176:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :126:22]
    casez (c_state)	// @[src/main/bus/AXI.scala:176:23, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :126:22]
      2'b00:
        casez_tmp_4 = isimem ? io_imem_wdata : _GEN_0 ? io_dmem_wdata : 32'h0;	// @[src/main/bus/AXI.scala:176:23, src/main/bus/Xbar_new.scala:35:21, :45:42, :61:20, :63:25, :65:{31,42}, :86:23, :126:22]
      2'b01:
        casez_tmp_4 = io_imem_wdata;	// @[src/main/bus/AXI.scala:176:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :126:22]
      2'b10:
        casez_tmp_4 = io_dmem_wdata;	// @[src/main/bus/AXI.scala:176:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :126:22]
      default:
        casez_tmp_4 = 32'h0;	// @[src/main/bus/AXI.scala:176:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :86:23, :126:22]
    endcase	// @[src/main/bus/AXI.scala:176:23, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :126:22]
  end // always_comb
  reg  [3:0]  casez_tmp_5;	// @[src/main/bus/Xbar_new.scala:61:20, :63:25]
  always_comb begin	// @[src/main/bus/AXI.scala:177:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :127:22]
    casez (c_state)	// @[src/main/bus/AXI.scala:177:23, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :127:22]
      2'b00:
        casez_tmp_5 = isimem ? io_imem_wstrb : _GEN_0 ? io_dmem_wstrb : 4'h0;	// @[src/main/bus/AXI.scala:149:25, :161:22, :168:23, :177:23, :186:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :35:21, :45:42, :61:20, :63:25, :65:{31,42}, :67:41, :104:21, :109:21, :115:21, :122:21, :127:22]
      2'b01:
        casez_tmp_5 = io_imem_wstrb;	// @[src/main/bus/AXI.scala:177:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :127:22]
      2'b10:
        casez_tmp_5 = io_dmem_wstrb;	// @[src/main/bus/AXI.scala:177:23, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :127:22]
      default:
        casez_tmp_5 = 4'h0;	// @[src/main/bus/AXI.scala:149:25, :161:22, :168:23, :177:23, :186:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :45:42, :61:20, :63:25, :65:42, :67:41, :104:21, :109:21, :115:21, :122:21, :127:22]
    endcase	// @[src/main/bus/AXI.scala:177:23, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :127:22]
  end // always_comb
  wire        _GEN_3 = _n_state_T_10 | _n_state_T_12;	// @[src/main/bus/Xbar_new.scala:45:42, :61:20, :134:25]
  reg  [31:0] casez_tmp_6;	// @[src/main/bus/Xbar_new.scala:61:20, :63:25]
  always_comb begin	// @[src/main/bus/Xbar_new.scala:61:20, :63:25, :134:25]
    casez (c_state)	// @[src/main/bus/Xbar_new.scala:27:26, :61:20, :63:25, :134:25]
      2'b00:
        casez_tmp_6 = _GEN_1 | ~_n_state_T_2 ? 32'h0 : io_dmem_araddr;	// @[src/main/bus/Xbar_new.scala:49:21, :61:20, :63:25, :65:42, :67:41, :86:23, :134:25]
      2'b01:
        casez_tmp_6 = 32'h0;	// @[src/main/bus/Xbar_new.scala:61:20, :63:25, :86:23, :134:25]
      2'b10:
        casez_tmp_6 = 32'h0;	// @[src/main/bus/Xbar_new.scala:61:20, :63:25, :86:23, :134:25]
      default:
        casez_tmp_6 = _GEN_3 | ~(&c_state) ? 32'h0 : io_dmem_araddr;	// @[src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :86:23, :134:25]
    endcase	// @[src/main/bus/Xbar_new.scala:27:26, :61:20, :63:25, :134:25]
  end // always_comb
  reg  [31:0] casez_tmp_7;	// @[src/main/bus/Xbar_new.scala:61:20, :63:25]
  always_comb begin	// @[src/main/bus/AXI.scala:157:22, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :100:23]
    casez (c_state)	// @[src/main/bus/AXI.scala:157:22, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :100:23]
      2'b00:
        casez_tmp_7 =
          isimem ? 32'h0 : _GEN_0 ? io_soc_rdata : _n_state_T_2 ? io_clint_rdata : 32'h0;	// @[src/main/bus/AXI.scala:157:22, src/main/bus/Xbar_new.scala:35:21, :45:42, :49:21, :61:20, :63:25, :65:{31,42}, :67:41, :86:23, :100:23]
      2'b01:
        casez_tmp_7 = 32'h0;	// @[src/main/bus/AXI.scala:157:22, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :86:23, :100:23]
      2'b10:
        casez_tmp_7 = io_soc_rdata;	// @[src/main/bus/AXI.scala:157:22, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :100:23]
      default:
        casez_tmp_7 = io_clint_rdata;	// @[src/main/bus/AXI.scala:157:22, src/main/bus/Xbar_new.scala:45:42, :61:20, :63:25, :100:23]
    endcase	// @[src/main/bus/AXI.scala:157:22, src/main/bus/Xbar_new.scala:27:26, :45:42, :61:20, :63:25, :100:23]
  end // always_comb
  wire        _GEN_4 = _GEN ? isimem | ~_GEN_0 : _n_state_T_10 | ~_n_state_T_12;	// @[src/main/bus/Xbar_new.scala:35:21, :45:42, :61:20, :63:25, :65:{31,42}, :101:23]
  always @(posedge clock) begin	// @[src/main/bus/Xbar_new.scala:22:7]
    if (reset)	// @[src/main/bus/Xbar_new.scala:22:7]
      c_state <= 2'h0;	// @[src/main/bus/AXI.scala:152:25, :158:22, :171:23, :184:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :27:26, :61:20, :65:42, :67:41, :101:23, :107:23, :118:24, :125:24]
    else	// @[src/main/bus/Xbar_new.scala:22:7]
      c_state <= n_state;	// @[src/main/bus/Xbar_new.scala:27:26, :28:30]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/bus/Xbar_new.scala:22:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/bus/Xbar_new.scala:22:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/bus/Xbar_new.scala:22:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/bus/Xbar_new.scala:22:7]
    initial begin	// @[src/main/bus/Xbar_new.scala:22:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/bus/Xbar_new.scala:22:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/bus/Xbar_new.scala:22:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/bus/Xbar_new.scala:22:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/bus/Xbar_new.scala:22:7]
        c_state = _RANDOM[/*Zero width*/ 1'b0][1:0];	// @[src/main/bus/Xbar_new.scala:22:7, :27:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/bus/Xbar_new.scala:22:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/bus/Xbar_new.scala:22:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_imem_arready =
    _GEN ? isimem & io_soc_arready : _n_state_T_10 & io_soc_arready;	// @[src/main/bus/AXI.scala:153:25, src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :85:25]
  assign io_imem_rdata = _GEN_2 ? io_soc_rdata : 32'h0;	// @[src/main/bus/AXI.scala:157:22, src/main/bus/Xbar_new.scala:22:7, :61:20, :63:25, :86:23]
  assign io_imem_rvalid = _GEN ? isimem & io_soc_rvalid : _n_state_T_10 & io_soc_rvalid;	// @[src/main/bus/AXI.scala:159:22, src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :88:24]
  assign io_dmem_arready =
    _GEN
      ? ~isimem & (_GEN_0 ? io_soc_arready : _n_state_T_2 & io_clint_arready)
      : ~_n_state_T_10 & (_n_state_T_12 ? io_soc_arready : (&c_state) & io_clint_arready);	// @[src/main/bus/AXI.scala:153:25, src/main/bus/Xbar_new.scala:22:7, :27:26, :35:21, :45:42, :49:21, :61:20, :63:25, :65:{31,42}, :67:41, :99:25]
  assign io_dmem_rdata = casez_tmp_7;	// @[src/main/bus/Xbar_new.scala:22:7, :61:20, :63:25]
  assign io_dmem_rresp = _GEN_4 ? 2'h0 : io_soc_rresp;	// @[src/main/bus/AXI.scala:152:25, :158:22, :171:23, :184:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :61:20, :63:25, :65:42, :67:41, :101:23, :107:23, :118:24, :125:24]
  assign io_dmem_rvalid =
    _GEN
      ? ~isimem & (_GEN_0 ? io_soc_rvalid : _n_state_T_2 & io_clint_rvalid)
      : ~_n_state_T_10 & (_n_state_T_12 ? io_soc_rvalid : (&c_state) & io_clint_rvalid);	// @[src/main/bus/AXI.scala:159:22, src/main/bus/Xbar_new.scala:22:7, :27:26, :35:21, :45:42, :49:21, :61:20, :63:25, :65:{31,42}, :67:41, :99:25, :102:24]
  assign io_dmem_awready =
    _GEN
      ? ~isimem & _GEN_0 & io_soc_awready
      : ~_n_state_T_10 & _n_state_T_12 & io_soc_awready;	// @[src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :65:{31,42}, :99:25, :105:25]
  assign io_dmem_wready =
    _GEN
      ? ~isimem & _GEN_0 & io_soc_wready
      : ~_n_state_T_10 & _n_state_T_12 & io_soc_wready;	// @[src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :65:{31,42}, :99:25, :106:24]
  assign io_dmem_bresp = _GEN_4 ? 2'h0 : io_soc_bresp;	// @[src/main/bus/AXI.scala:152:25, :158:22, :171:23, :184:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :61:20, :63:25, :65:42, :67:41, :101:23, :107:23, :118:24, :125:24]
  assign io_dmem_bvalid =
    _GEN
      ? ~isimem & _GEN_0 & io_soc_bvalid
      : ~_n_state_T_10 & _n_state_T_12 & io_soc_bvalid;	// @[src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :65:{31,42}, :99:25, :108:24]
  assign io_soc_araddr = casez_tmp_0;	// @[src/main/bus/Xbar_new.scala:22:7, :61:20, :63:25]
  assign io_soc_arvalid =
    _GEN
      ? (isimem ? io_imem_arvalid : _GEN_0 & io_dmem_arvalid)
      : _n_state_T_10 ? io_imem_arvalid : _n_state_T_12 & io_dmem_arvalid;	// @[src/main/bus/AXI.scala:148:25, src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :65:{31,42}, :114:24]
  assign io_soc_arid = _GEN_2 ? io_imem_arid : 4'h0;	// @[src/main/bus/AXI.scala:149:25, :157:22, :161:22, :168:23, :186:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :61:20, :63:25, :65:42, :67:41, :86:23, :104:21, :109:21, :115:21, :122:21]
  assign io_soc_arlen = _GEN_2 ? io_imem_arlen : 8'h0;	// @[src/main/bus/AXI.scala:150:25, :157:22, :169:23, src/main/bus/Xbar_new.scala:22:7, :23:16, :61:20, :63:25, :65:42, :86:23, :116:22, :123:22]
  assign io_soc_arsize = casez_tmp_1;	// @[src/main/bus/Xbar_new.scala:22:7, :61:20, :63:25]
  assign io_soc_arburst = _GEN_2 ? io_imem_arburst : 2'h0;	// @[src/main/bus/AXI.scala:152:25, :157:22, :158:22, :171:23, :184:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :61:20, :63:25, :65:42, :67:41, :86:23, :101:23, :107:23, :118:24, :125:24]
  assign io_soc_rready =
    _GEN
      ? (isimem ? io_imem_rready : _GEN_0 & io_dmem_rready)
      : _n_state_T_10 ? io_imem_rready : _n_state_T_12 & io_dmem_rready;	// @[src/main/bus/AXI.scala:162:22, src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :65:{31,42}, :119:23]
  assign io_soc_awaddr = casez_tmp_2;	// @[src/main/bus/Xbar_new.scala:22:7, :61:20, :63:25]
  assign io_soc_awvalid =
    _GEN
      ? (isimem ? io_imem_awvalid : _GEN_0 & io_dmem_awvalid)
      : _n_state_T_10 ? io_imem_awvalid : _n_state_T_12 & io_dmem_awvalid;	// @[src/main/bus/AXI.scala:167:23, src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :65:{31,42}, :121:24]
  assign io_soc_awid = _GEN_2 ? io_imem_awid : 4'h0;	// @[src/main/bus/AXI.scala:149:25, :157:22, :161:22, :168:23, :186:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :61:20, :63:25, :65:42, :67:41, :86:23, :104:21, :109:21, :115:21, :122:21]
  assign io_soc_awlen = _GEN_2 ? io_imem_awlen : 8'h0;	// @[src/main/bus/AXI.scala:150:25, :157:22, :169:23, src/main/bus/Xbar_new.scala:22:7, :23:16, :61:20, :63:25, :65:42, :86:23, :116:22, :123:22]
  assign io_soc_awsize = casez_tmp_3;	// @[src/main/bus/Xbar_new.scala:22:7, :61:20, :63:25]
  assign io_soc_awburst = _GEN_2 ? io_imem_awburst : 2'h0;	// @[src/main/bus/AXI.scala:152:25, :157:22, :158:22, :171:23, :184:22, src/main/bus/Xbar_new.scala:22:7, :23:16, :61:20, :63:25, :65:42, :67:41, :86:23, :101:23, :107:23, :118:24, :125:24]
  assign io_soc_wdata = casez_tmp_4;	// @[src/main/bus/Xbar_new.scala:22:7, :61:20, :63:25]
  assign io_soc_wstrb = casez_tmp_5;	// @[src/main/bus/Xbar_new.scala:22:7, :61:20, :63:25]
  assign io_soc_wvalid =
    _GEN
      ? (isimem ? io_imem_wvalid : _GEN_0 & io_dmem_wvalid)
      : _n_state_T_10 ? io_imem_wvalid : _n_state_T_12 & io_dmem_wvalid;	// @[src/main/bus/AXI.scala:178:23, src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :65:{31,42}, :128:23]
  assign io_soc_wlast =
    _GEN
      ? (isimem ? io_imem_wlast : _GEN_0)
      : _n_state_T_10 ? io_imem_wlast : _n_state_T_12;	// @[src/main/bus/AXI.scala:179:23, src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :65:{31,42}]
  assign io_soc_bready =
    _GEN
      ? (isimem ? io_imem_bready : _GEN_0 & io_dmem_bready)
      : _n_state_T_10 ? io_imem_bready : _n_state_T_12 & io_dmem_bready;	// @[src/main/bus/AXI.scala:187:22, src/main/bus/Xbar_new.scala:22:7, :35:21, :45:42, :61:20, :63:25, :65:{31,42}, :130:23]
  assign io_clint_araddr = casez_tmp_6;	// @[src/main/bus/Xbar_new.scala:22:7, :61:20, :63:25]
  assign io_clint_arvalid =
    _GEN
      ? ~_GEN_1 & _n_state_T_2 & io_dmem_arvalid
      : ~_GEN_3 & (&c_state) & io_dmem_arvalid;	// @[src/main/bus/Xbar_new.scala:22:7, :27:26, :45:42, :49:21, :61:20, :63:25, :65:42, :67:41, :134:25, :135:26]
  assign io_clint_rready =
    _GEN
      ? ~_GEN_1 & _n_state_T_2 & io_dmem_rready
      : ~_GEN_3 & (&c_state) & io_dmem_rready;	// @[src/main/bus/Xbar_new.scala:22:7, :27:26, :45:42, :49:21, :61:20, :63:25, :65:42, :67:41, :134:25, :135:26, :140:25]
endmodule

